// Giao diện WinForms tạo bằng các control và container chuẩn để Visual Studio Designer hiển thị.
// Có thể chỉnh trực tiếp vị trí, kích thước, Text trong tab Design.
using System;
using System.Drawing;
using System.Windows.Forms;

namespace QuanLyCongTyDuLich.Forms
{
    public partial class FrmChuyenLe
    {
        private System.ComponentModel.IContainer components = null;
        private TextBox txtMa;
        private ComboBox cboTour;
        private DateTimePicker dtDi;
        private Label lblNgayVe;
        private TextBox txtDon;
        private Button btnThem;
        private Button btnDongDK;
        private DataGridView dgv;
        private Button btnDong;
        private TableLayoutPanel mainLayout;
        private Label lblTieuDe;
        private FlowLayoutPanel flowFields;
        private Panel panField0;
        private Label lblField0;
        private Panel panField1;
        private Label lblField1;
        private Panel panField2;
        private Label lblField2;
        private Panel panField3;
        private Label lblField3;
        private Panel panField4;
        private Label lblField4;
        private Panel panField5;
        private Label lblField5;
        private Panel panField6;
        private Label lblField6;
        private FlowLayoutPanel footerLayout;

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null) this.components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.txtMa = new TextBox();
            this.txtMa.Name = "txtMa";
            this.txtMa.Size = new Size(205, 29);
            this.cboTour = new ComboBox();
            this.cboTour.Name = "cboTour";
            this.cboTour.DropDownStyle = ComboBoxStyle.DropDownList;
            this.dtDi = new DateTimePicker();
            this.dtDi.Name = "dtDi";
            this.dtDi.Format = DateTimePickerFormat.Short;
            this.dtDi.Size = new Size(205, 30);
            this.lblNgayVe = new Label();
            this.lblNgayVe.Name = "lblNgayVe";
            this.lblNgayVe.Text = "-";
            this.lblNgayVe.Size = new Size(205, 30);
            this.lblNgayVe.TextAlign = ContentAlignment.MiddleLeft;
            this.txtDon = new TextBox();
            this.txtDon.Name = "txtDon";
            this.txtDon.Size = new Size(205, 29);
            this.btnThem = new Button();
            this.btnThem.Name = "btnThem";
            this.btnThem.Text = "Tạo chuyến";
            this.btnThem.Size = new Size(190, 36);
            this.btnThem.FlatStyle = FlatStyle.Standard;
            this.btnDongDK = new Button();
            this.btnDongDK.Name = "btnDongDK";
            this.btnDongDK.Text = "Đóng đăng ký";
            this.btnDongDK.Size = new Size(190, 36);
            this.btnDongDK.FlatStyle = FlatStyle.Standard;
            this.dgv = new DataGridView();
            this.dgv.Name = "dgv";
            this.dgv.Dock = DockStyle.Fill;
            this.dgv.BackgroundColor = Color.White;
            this.dgv.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
            this.dgv.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgv.MultiSelect = false;
            this.dgv.RowHeadersVisible = false;
            this.dgv.AllowUserToAddRows = false;
            this.dgv.AllowUserToDeleteRows = false;
            this.dgv.ReadOnly = true;
            this.btnDong = new Button();
            this.btnDong.Name = "btnDong";
            this.btnDong.Text = "Đóng";
            this.btnDong.Size = new Size(190, 36);
            this.btnDong.FlatStyle = FlatStyle.Standard;
            this.cboTour.SelectedIndexChanged += new EventHandler(this.TinhNgayVe);
            this.dtDi.ValueChanged += new EventHandler(this.TinhNgayVe);
            this.btnThem.Click += new EventHandler(this.btnThem_Click);
            this.btnDongDK.Click += new EventHandler(this.btnDongDK_Click);
            this.btnDong.Click += new EventHandler(this.btnDong_Click);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.ClientSize = new Size(1120, 760);
            this.MinimumSize = new Size(800, 600);
            this.StartPosition = FormStartPosition.CenterScreen;
            this.Font = new Font("Segoe UI", 9.5f);
            this.Text = "Lịch chuyến khách lẻ";
            this.Load += new EventHandler(this.FrmChuyenLe_Load);
            this.mainLayout = new TableLayoutPanel();
            this.mainLayout.Name = "mainLayout";
            this.mainLayout.Dock = DockStyle.Fill;
            this.mainLayout.Padding = new Padding(12);
            this.mainLayout.ColumnCount = 1;
            this.mainLayout.RowCount = 4;
            this.mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 55F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 180F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 55F));
            this.Controls.Add(this.mainLayout);
            this.lblTieuDe = new Label();
            this.lblTieuDe.Name = "lblTieuDe";
            this.lblTieuDe.Text = "Lịch chuyến khách lẻ";
            this.lblTieuDe.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
            this.lblTieuDe.ForeColor = Color.FromArgb(33, 65, 94);
            this.lblTieuDe.Dock = DockStyle.Fill;
            this.lblTieuDe.TextAlign = ContentAlignment.MiddleCenter;
            this.mainLayout.Controls.Add(this.lblTieuDe, 0, 0);
            this.flowFields = new FlowLayoutPanel();
            this.flowFields.Name = "flowFields";
            this.flowFields.Dock = DockStyle.Fill;
            this.flowFields.AutoScroll = true;
            this.flowFields.WrapContents = true;
            this.flowFields.Padding = new Padding(6);
            this.flowFields.FlowDirection = FlowDirection.LeftToRight;
            this.panField0 = new Panel();
            this.panField0.Name = "panField0";
            this.panField0.Size = new Size(230, 67);
            this.panField0.Margin = new Padding(5, 5, 5, 2);
            this.lblField0 = new Label();
            this.lblField0.Name = "lblField0";
            this.lblField0.Text = "Mã chuyến";
            this.lblField0.AutoSize = false;
            this.lblField0.Size = new Size(215, 20);
            this.lblField0.Location = new Point(6, 2);
            this.panField0.Controls.Add(this.lblField0);
            this.txtMa.Location = new Point(6, 27);
            this.txtMa.Size = new Size(210, 28);
            this.panField0.Controls.Add(this.txtMa);
            this.flowFields.Controls.Add(this.panField0);
            this.panField1 = new Panel();
            this.panField1.Name = "panField1";
            this.panField1.Size = new Size(230, 67);
            this.panField1.Margin = new Padding(5, 5, 5, 2);
            this.lblField1 = new Label();
            this.lblField1.Name = "lblField1";
            this.lblField1.Text = "Tour";
            this.lblField1.AutoSize = false;
            this.lblField1.Size = new Size(215, 20);
            this.lblField1.Location = new Point(6, 2);
            this.panField1.Controls.Add(this.lblField1);
            this.cboTour.Location = new Point(6, 27);
            this.cboTour.Size = new Size(210, 28);
            this.panField1.Controls.Add(this.cboTour);
            this.flowFields.Controls.Add(this.panField1);
            this.panField2 = new Panel();
            this.panField2.Name = "panField2";
            this.panField2.Size = new Size(230, 67);
            this.panField2.Margin = new Padding(5, 5, 5, 2);
            this.lblField2 = new Label();
            this.lblField2.Name = "lblField2";
            this.lblField2.Text = "Ngày đi";
            this.lblField2.AutoSize = false;
            this.lblField2.Size = new Size(215, 20);
            this.lblField2.Location = new Point(6, 2);
            this.panField2.Controls.Add(this.lblField2);
            this.dtDi.Location = new Point(6, 27);
            this.dtDi.Size = new Size(210, 28);
            this.panField2.Controls.Add(this.dtDi);
            this.flowFields.Controls.Add(this.panField2);
            this.panField3 = new Panel();
            this.panField3.Name = "panField3";
            this.panField3.Size = new Size(230, 67);
            this.panField3.Margin = new Padding(5, 5, 5, 2);
            this.lblField3 = new Label();
            this.lblField3.Name = "lblField3";
            this.lblField3.Text = "Ngày về";
            this.lblField3.AutoSize = false;
            this.lblField3.Size = new Size(215, 20);
            this.lblField3.Location = new Point(6, 2);
            this.panField3.Controls.Add(this.lblField3);
            this.lblNgayVe.Location = new Point(6, 27);
            this.lblNgayVe.Size = new Size(210, 29);
            this.panField3.Controls.Add(this.lblNgayVe);
            this.flowFields.Controls.Add(this.panField3);
            this.panField4 = new Panel();
            this.panField4.Name = "panField4";
            this.panField4.Size = new Size(230, 67);
            this.panField4.Margin = new Padding(5, 5, 5, 2);
            this.lblField4 = new Label();
            this.lblField4.Name = "lblField4";
            this.lblField4.Text = "Địa điểm đón";
            this.lblField4.AutoSize = false;
            this.lblField4.Size = new Size(215, 20);
            this.lblField4.Location = new Point(6, 2);
            this.panField4.Controls.Add(this.lblField4);
            this.txtDon.Location = new Point(6, 27);
            this.txtDon.Size = new Size(210, 28);
            this.panField4.Controls.Add(this.txtDon);
            this.flowFields.Controls.Add(this.panField4);
            this.panField5 = new Panel();
            this.panField5.Name = "panField5";
            this.panField5.Size = new Size(230, 67);
            this.panField5.Margin = new Padding(5, 5, 5, 2);
            this.lblField5 = new Label();
            this.lblField5.Name = "lblField5";
            this.lblField5.Text = "Tạo chuyến";
            this.lblField5.AutoSize = false;
            this.lblField5.Size = new Size(215, 20);
            this.lblField5.Location = new Point(6, 2);
            this.panField5.Controls.Add(this.lblField5);
            this.btnThem.Location = new Point(6, 27);
            this.btnThem.Size = new Size(210, 34);
            this.panField5.Controls.Add(this.btnThem);
            this.flowFields.Controls.Add(this.panField5);
            this.panField6 = new Panel();
            this.panField6.Name = "panField6";
            this.panField6.Size = new Size(230, 67);
            this.panField6.Margin = new Padding(5, 5, 5, 2);
            this.lblField6 = new Label();
            this.lblField6.Name = "lblField6";
            this.lblField6.Text = "Đóng đăng ký";
            this.lblField6.AutoSize = false;
            this.lblField6.Size = new Size(215, 20);
            this.lblField6.Location = new Point(6, 2);
            this.panField6.Controls.Add(this.lblField6);
            this.btnDongDK.Location = new Point(6, 27);
            this.btnDongDK.Size = new Size(210, 34);
            this.panField6.Controls.Add(this.btnDongDK);
            this.flowFields.Controls.Add(this.panField6);
            this.mainLayout.Controls.Add(this.flowFields, 0, 1);
            this.mainLayout.Controls.Add(this.dgv, 0, 2);
            this.footerLayout = new FlowLayoutPanel();
            this.footerLayout.Name = "footerLayout";
            this.footerLayout.Dock = DockStyle.Fill;
            this.footerLayout.FlowDirection = FlowDirection.RightToLeft;
            this.footerLayout.Padding = new Padding(6);
            this.btnDong.Size = new Size(120, 35);
            this.footerLayout.Controls.Add(this.btnDong);
            this.mainLayout.Controls.Add(this.footerLayout, 0, 3);
            this.ResumeLayout(false);
        }
    }
}
