// Giao diện WinForms tạo bằng các control và container chuẩn để Visual Studio Designer hiển thị.
// Có thể chỉnh trực tiếp vị trí, kích thước, Text trong tab Design.
using System;
using System.Drawing;
using System.Windows.Forms;

namespace QuanLyCongTyDuLich.Forms
{
    public partial class FrmDangKyDoan
    {
        private System.ComponentModel.IContainer components = null;
        private GroupBox grpDoan;
        private TextBox txtMaDoan;
        private TextBox txtTenCQ;
        private TextBox txtDiaChi;
        private TextBox txtDT;
        private TextBox txtDaiDien;
        private GroupBox grpDangKy;
        private TextBox txtSo;
        private ComboBox cboTour;
        private DateTimePicker dtDi;
        private NumericUpDown numNguoi;
        private TextBox txtDon;
        private NumericUpDown numCoc;
        private CheckBox chkBH;
        private Label lblKetThuc;
        private Label lblTong;
        private DataGridView dgvThanhVien;
        private Button btnDangKy;
        private Button btnHuy;
        private DataGridView dgv;
        private Button btnDong;
        private TableLayoutPanel mainLayout;
        private Label lblTieuDe;
        private TableLayoutPanel twoGroups;
        private FlowLayoutPanel fieldsGroup0;
        private Panel panGroup0Field0;
        private Label lblGroup0Field0;
        private Panel panGroup0Field1;
        private Label lblGroup0Field1;
        private Panel panGroup0Field2;
        private Label lblGroup0Field2;
        private Panel panGroup0Field3;
        private Label lblGroup0Field3;
        private Panel panGroup0Field4;
        private Label lblGroup0Field4;
        private FlowLayoutPanel fieldsGroup1;
        private Panel panGroup1Field0;
        private Label lblGroup1Field0;
        private Panel panGroup1Field1;
        private Label lblGroup1Field1;
        private Panel panGroup1Field2;
        private Label lblGroup1Field2;
        private Panel panGroup1Field3;
        private Label lblGroup1Field3;
        private Panel panGroup1Field4;
        private Label lblGroup1Field4;
        private Panel panGroup1Field5;
        private Label lblGroup1Field5;
        private Panel panGroup1Field7;
        private Label lblGroup1Field7;
        private Panel panGroup1Field8;
        private Label lblGroup1Field8;
        private GroupBox grpThanhVien;
        private FlowLayoutPanel actions;
        private FlowLayoutPanel footerLayout;

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null) this.components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.grpDoan = new GroupBox();
            this.grpDoan.Name = "grpDoan";
            this.txtMaDoan = new TextBox();
            this.txtMaDoan.Name = "txtMaDoan";
            this.txtMaDoan.Size = new Size(205, 29);
            this.txtTenCQ = new TextBox();
            this.txtTenCQ.Name = "txtTenCQ";
            this.txtTenCQ.Size = new Size(205, 29);
            this.txtDiaChi = new TextBox();
            this.txtDiaChi.Name = "txtDiaChi";
            this.txtDiaChi.Size = new Size(205, 29);
            this.txtDT = new TextBox();
            this.txtDT.Name = "txtDT";
            this.txtDT.Size = new Size(205, 29);
            this.txtDaiDien = new TextBox();
            this.txtDaiDien.Name = "txtDaiDien";
            this.txtDaiDien.Size = new Size(205, 29);
            this.grpDangKy = new GroupBox();
            this.grpDangKy.Name = "grpDangKy";
            this.txtSo = new TextBox();
            this.txtSo.Name = "txtSo";
            this.txtSo.Size = new Size(205, 29);
            this.cboTour = new ComboBox();
            this.cboTour.Name = "cboTour";
            this.cboTour.DropDownStyle = ComboBoxStyle.DropDownList;
            this.dtDi = new DateTimePicker();
            this.dtDi.Name = "dtDi";
            this.dtDi.Format = DateTimePickerFormat.Short;
            this.dtDi.Size = new Size(205, 30);
            this.numNguoi = new NumericUpDown();
            this.numNguoi.Name = "numNguoi";
            this.numNguoi.Maximum = 10000;
            this.numNguoi.Minimum = 13;
            this.numNguoi.Size = new Size(205, 28);
            this.txtDon = new TextBox();
            this.txtDon.Name = "txtDon";
            this.txtDon.Size = new Size(205, 29);
            this.numCoc = new NumericUpDown();
            this.numCoc.Name = "numCoc";
            this.numCoc.Maximum = 100000000000M;
            this.numCoc.Minimum = 0;
            this.numCoc.Size = new Size(205, 28);
            this.chkBH = new CheckBox();
            this.chkBH.Name = "chkBH";
            this.chkBH.AutoSize = true;
            this.lblKetThuc = new Label();
            this.lblKetThuc.Name = "lblKetThuc";
            this.lblKetThuc.Text = "-";
            this.lblKetThuc.Size = new Size(205, 30);
            this.lblKetThuc.TextAlign = ContentAlignment.MiddleLeft;
            this.lblTong = new Label();
            this.lblTong.Name = "lblTong";
            this.lblTong.Text = "-";
            this.lblTong.Size = new Size(205, 30);
            this.lblTong.TextAlign = ContentAlignment.MiddleLeft;
            this.dgvThanhVien = new DataGridView();
            this.dgvThanhVien.Name = "dgvThanhVien";
            this.dgvThanhVien.Dock = DockStyle.Fill;
            this.dgvThanhVien.BackgroundColor = Color.White;
            this.dgvThanhVien.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
            this.dgvThanhVien.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvThanhVien.MultiSelect = false;
            this.dgvThanhVien.RowHeadersVisible = false;
            this.dgvThanhVien.AllowUserToAddRows = true;
            this.dgvThanhVien.AllowUserToDeleteRows = true;
            this.dgvThanhVien.ReadOnly = false;
            this.btnDangKy = new Button();
            this.btnDangKy.Name = "btnDangKy";
            this.btnDangKy.Text = "Lập phiếu đăng ký";
            this.btnDangKy.Size = new Size(190, 36);
            this.btnDangKy.FlatStyle = FlatStyle.Standard;
            this.btnHuy = new Button();
            this.btnHuy.Name = "btnHuy";
            this.btnHuy.Text = "Hủy phiếu (mất cọc)";
            this.btnHuy.Size = new Size(190, 36);
            this.btnHuy.FlatStyle = FlatStyle.Standard;
            this.dgv = new DataGridView();
            this.dgv.Name = "dgv";
            this.dgv.Dock = DockStyle.Fill;
            this.dgv.BackgroundColor = Color.White;
            this.dgv.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
            this.dgv.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgv.MultiSelect = false;
            this.dgv.RowHeadersVisible = false;
            this.dgv.AllowUserToAddRows = false;
            this.dgv.AllowUserToDeleteRows = false;
            this.dgv.ReadOnly = true;
            this.btnDong = new Button();
            this.btnDong.Name = "btnDong";
            this.btnDong.Text = "Đóng";
            this.btnDong.Size = new Size(190, 36);
            this.btnDong.FlatStyle = FlatStyle.Standard;
            this.cboTour.SelectedIndexChanged += new EventHandler(this.TinhTong);
            this.dtDi.ValueChanged += new EventHandler(this.TinhTong);
            this.numNguoi.ValueChanged += new EventHandler(this.TinhTong);
            this.chkBH.CheckedChanged += new EventHandler(this.chkBH_CheckedChanged);
            this.btnDangKy.Click += new EventHandler(this.btnDangKy_Click);
            this.btnHuy.Click += new EventHandler(this.btnHuy_Click);
            this.btnDong.Click += new EventHandler(this.btnDong_Click);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.ClientSize = new Size(1120, 760);
            this.MinimumSize = new Size(800, 600);
            this.StartPosition = FormStartPosition.CenterScreen;
            this.Font = new Font("Segoe UI", 9.5f);
            this.Text = "Đăng ký khách đoàn";
            this.Load += new EventHandler(this.FrmDangKyDoan_Load);
            this.mainLayout = new TableLayoutPanel();
            this.mainLayout.Name = "mainLayout";
            this.mainLayout.Dock = DockStyle.Fill;
            this.mainLayout.Padding = new Padding(12);
            this.mainLayout.ColumnCount = 1;
            this.mainLayout.RowCount = 6;
            this.mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 55F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 230F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 190F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 55F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 55F));
            this.Controls.Add(this.mainLayout);
            this.lblTieuDe = new Label();
            this.lblTieuDe.Name = "lblTieuDe";
            this.lblTieuDe.Text = "Đăng ký khách đoàn";
            this.lblTieuDe.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
            this.lblTieuDe.ForeColor = Color.FromArgb(33, 65, 94);
            this.lblTieuDe.Dock = DockStyle.Fill;
            this.lblTieuDe.TextAlign = ContentAlignment.MiddleCenter;
            this.mainLayout.Controls.Add(this.lblTieuDe, 0, 0);
            this.twoGroups = new TableLayoutPanel();
            this.twoGroups.Name = "twoGroups";
            this.twoGroups.Dock = DockStyle.Fill;
            this.twoGroups.ColumnCount = 2;
            this.twoGroups.RowCount = 1;
            this.twoGroups.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            this.twoGroups.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            this.grpDoan.Text = "Thông tin đoàn khách";
            this.grpDoan.Dock = DockStyle.Fill;
            this.fieldsGroup0 = new FlowLayoutPanel();
            this.fieldsGroup0.Name = "fieldsGroup0";
            this.fieldsGroup0.Dock = DockStyle.Fill;
            this.fieldsGroup0.AutoScroll = true;
            this.fieldsGroup0.WrapContents = true;
            this.fieldsGroup0.Padding = new Padding(6);
            this.fieldsGroup0.FlowDirection = FlowDirection.LeftToRight;
            this.panGroup0Field0 = new Panel();
            this.panGroup0Field0.Name = "panGroup0Field0";
            this.panGroup0Field0.Size = new Size(230, 67);
            this.panGroup0Field0.Margin = new Padding(5, 5, 5, 2);
            this.lblGroup0Field0 = new Label();
            this.lblGroup0Field0.Name = "lblGroup0Field0";
            this.lblGroup0Field0.Text = "Mã đoàn";
            this.lblGroup0Field0.AutoSize = false;
            this.lblGroup0Field0.Size = new Size(215, 20);
            this.lblGroup0Field0.Location = new Point(6, 2);
            this.panGroup0Field0.Controls.Add(this.lblGroup0Field0);
            this.txtMaDoan.Location = new Point(6, 27);
            this.txtMaDoan.Size = new Size(210, 28);
            this.panGroup0Field0.Controls.Add(this.txtMaDoan);
            this.fieldsGroup0.Controls.Add(this.panGroup0Field0);
            this.panGroup0Field1 = new Panel();
            this.panGroup0Field1.Name = "panGroup0Field1";
            this.panGroup0Field1.Size = new Size(230, 67);
            this.panGroup0Field1.Margin = new Padding(5, 5, 5, 2);
            this.lblGroup0Field1 = new Label();
            this.lblGroup0Field1.Name = "lblGroup0Field1";
            this.lblGroup0Field1.Text = "Cơ quan / gia đình";
            this.lblGroup0Field1.AutoSize = false;
            this.lblGroup0Field1.Size = new Size(215, 20);
            this.lblGroup0Field1.Location = new Point(6, 2);
            this.panGroup0Field1.Controls.Add(this.lblGroup0Field1);
            this.txtTenCQ.Location = new Point(6, 27);
            this.txtTenCQ.Size = new Size(210, 28);
            this.panGroup0Field1.Controls.Add(this.txtTenCQ);
            this.fieldsGroup0.Controls.Add(this.panGroup0Field1);
            this.panGroup0Field2 = new Panel();
            this.panGroup0Field2.Name = "panGroup0Field2";
            this.panGroup0Field2.Size = new Size(230, 67);
            this.panGroup0Field2.Margin = new Padding(5, 5, 5, 2);
            this.lblGroup0Field2 = new Label();
            this.lblGroup0Field2.Name = "lblGroup0Field2";
            this.lblGroup0Field2.Text = "Địa chỉ";
            this.lblGroup0Field2.AutoSize = false;
            this.lblGroup0Field2.Size = new Size(215, 20);
            this.lblGroup0Field2.Location = new Point(6, 2);
            this.panGroup0Field2.Controls.Add(this.lblGroup0Field2);
            this.txtDiaChi.Location = new Point(6, 27);
            this.txtDiaChi.Size = new Size(210, 28);
            this.panGroup0Field2.Controls.Add(this.txtDiaChi);
            this.fieldsGroup0.Controls.Add(this.panGroup0Field2);
            this.panGroup0Field3 = new Panel();
            this.panGroup0Field3.Name = "panGroup0Field3";
            this.panGroup0Field3.Size = new Size(230, 67);
            this.panGroup0Field3.Margin = new Padding(5, 5, 5, 2);
            this.lblGroup0Field3 = new Label();
            this.lblGroup0Field3.Name = "lblGroup0Field3";
            this.lblGroup0Field3.Text = "Điện thoại";
            this.lblGroup0Field3.AutoSize = false;
            this.lblGroup0Field3.Size = new Size(215, 20);
            this.lblGroup0Field3.Location = new Point(6, 2);
            this.panGroup0Field3.Controls.Add(this.lblGroup0Field3);
            this.txtDT.Location = new Point(6, 27);
            this.txtDT.Size = new Size(210, 28);
            this.panGroup0Field3.Controls.Add(this.txtDT);
            this.fieldsGroup0.Controls.Add(this.panGroup0Field3);
            this.panGroup0Field4 = new Panel();
            this.panGroup0Field4.Name = "panGroup0Field4";
            this.panGroup0Field4.Size = new Size(230, 67);
            this.panGroup0Field4.Margin = new Padding(5, 5, 5, 2);
            this.lblGroup0Field4 = new Label();
            this.lblGroup0Field4.Name = "lblGroup0Field4";
            this.lblGroup0Field4.Text = "Người đại diện";
            this.lblGroup0Field4.AutoSize = false;
            this.lblGroup0Field4.Size = new Size(215, 20);
            this.lblGroup0Field4.Location = new Point(6, 2);
            this.panGroup0Field4.Controls.Add(this.lblGroup0Field4);
            this.txtDaiDien.Location = new Point(6, 27);
            this.txtDaiDien.Size = new Size(210, 28);
            this.panGroup0Field4.Controls.Add(this.txtDaiDien);
            this.fieldsGroup0.Controls.Add(this.panGroup0Field4);
            this.grpDoan.Controls.Add(this.fieldsGroup0);
            this.twoGroups.Controls.Add(this.grpDoan, 0, 0);
            this.grpDangKy.Text = "Đăng ký tour";
            this.grpDangKy.Dock = DockStyle.Fill;
            this.fieldsGroup1 = new FlowLayoutPanel();
            this.fieldsGroup1.Name = "fieldsGroup1";
            this.fieldsGroup1.Dock = DockStyle.Fill;
            this.fieldsGroup1.AutoScroll = true;
            this.fieldsGroup1.WrapContents = true;
            this.fieldsGroup1.Padding = new Padding(6);
            this.fieldsGroup1.FlowDirection = FlowDirection.LeftToRight;
            this.panGroup1Field0 = new Panel();
            this.panGroup1Field0.Name = "panGroup1Field0";
            this.panGroup1Field0.Size = new Size(230, 67);
            this.panGroup1Field0.Margin = new Padding(5, 5, 5, 2);
            this.lblGroup1Field0 = new Label();
            this.lblGroup1Field0.Name = "lblGroup1Field0";
            this.lblGroup1Field0.Text = "Số phiếu";
            this.lblGroup1Field0.AutoSize = false;
            this.lblGroup1Field0.Size = new Size(215, 20);
            this.lblGroup1Field0.Location = new Point(6, 2);
            this.panGroup1Field0.Controls.Add(this.lblGroup1Field0);
            this.txtSo.Location = new Point(6, 27);
            this.txtSo.Size = new Size(210, 28);
            this.panGroup1Field0.Controls.Add(this.txtSo);
            this.fieldsGroup1.Controls.Add(this.panGroup1Field0);
            this.panGroup1Field1 = new Panel();
            this.panGroup1Field1.Name = "panGroup1Field1";
            this.panGroup1Field1.Size = new Size(230, 67);
            this.panGroup1Field1.Margin = new Padding(5, 5, 5, 2);
            this.lblGroup1Field1 = new Label();
            this.lblGroup1Field1.Name = "lblGroup1Field1";
            this.lblGroup1Field1.Text = "Tour";
            this.lblGroup1Field1.AutoSize = false;
            this.lblGroup1Field1.Size = new Size(215, 20);
            this.lblGroup1Field1.Location = new Point(6, 2);
            this.panGroup1Field1.Controls.Add(this.lblGroup1Field1);
            this.cboTour.Location = new Point(6, 27);
            this.cboTour.Size = new Size(210, 28);
            this.panGroup1Field1.Controls.Add(this.cboTour);
            this.fieldsGroup1.Controls.Add(this.panGroup1Field1);
            this.panGroup1Field2 = new Panel();
            this.panGroup1Field2.Name = "panGroup1Field2";
            this.panGroup1Field2.Size = new Size(230, 67);
            this.panGroup1Field2.Margin = new Padding(5, 5, 5, 2);
            this.lblGroup1Field2 = new Label();
            this.lblGroup1Field2.Name = "lblGroup1Field2";
            this.lblGroup1Field2.Text = "Ngày đi";
            this.lblGroup1Field2.AutoSize = false;
            this.lblGroup1Field2.Size = new Size(215, 20);
            this.lblGroup1Field2.Location = new Point(6, 2);
            this.panGroup1Field2.Controls.Add(this.lblGroup1Field2);
            this.dtDi.Location = new Point(6, 27);
            this.dtDi.Size = new Size(210, 28);
            this.panGroup1Field2.Controls.Add(this.dtDi);
            this.fieldsGroup1.Controls.Add(this.panGroup1Field2);
            this.panGroup1Field3 = new Panel();
            this.panGroup1Field3.Name = "panGroup1Field3";
            this.panGroup1Field3.Size = new Size(230, 67);
            this.panGroup1Field3.Margin = new Padding(5, 5, 5, 2);
            this.lblGroup1Field3 = new Label();
            this.lblGroup1Field3.Name = "lblGroup1Field3";
            this.lblGroup1Field3.Text = "Số người";
            this.lblGroup1Field3.AutoSize = false;
            this.lblGroup1Field3.Size = new Size(215, 20);
            this.lblGroup1Field3.Location = new Point(6, 2);
            this.panGroup1Field3.Controls.Add(this.lblGroup1Field3);
            this.numNguoi.Location = new Point(6, 27);
            this.numNguoi.Size = new Size(210, 28);
            this.panGroup1Field3.Controls.Add(this.numNguoi);
            this.fieldsGroup1.Controls.Add(this.panGroup1Field3);
            this.panGroup1Field4 = new Panel();
            this.panGroup1Field4.Name = "panGroup1Field4";
            this.panGroup1Field4.Size = new Size(230, 67);
            this.panGroup1Field4.Margin = new Padding(5, 5, 5, 2);
            this.lblGroup1Field4 = new Label();
            this.lblGroup1Field4.Name = "lblGroup1Field4";
            this.lblGroup1Field4.Text = "Địa điểm đón";
            this.lblGroup1Field4.AutoSize = false;
            this.lblGroup1Field4.Size = new Size(215, 20);
            this.lblGroup1Field4.Location = new Point(6, 2);
            this.panGroup1Field4.Controls.Add(this.lblGroup1Field4);
            this.txtDon.Location = new Point(6, 27);
            this.txtDon.Size = new Size(210, 28);
            this.panGroup1Field4.Controls.Add(this.txtDon);
            this.fieldsGroup1.Controls.Add(this.panGroup1Field4);
            this.panGroup1Field5 = new Panel();
            this.panGroup1Field5.Name = "panGroup1Field5";
            this.panGroup1Field5.Size = new Size(230, 67);
            this.panGroup1Field5.Margin = new Padding(5, 5, 5, 2);
            this.lblGroup1Field5 = new Label();
            this.lblGroup1Field5.Name = "lblGroup1Field5";
            this.lblGroup1Field5.Text = "Tiền cọc";
            this.lblGroup1Field5.AutoSize = false;
            this.lblGroup1Field5.Size = new Size(215, 20);
            this.lblGroup1Field5.Location = new Point(6, 2);
            this.panGroup1Field5.Controls.Add(this.lblGroup1Field5);
            this.numCoc.Location = new Point(6, 27);
            this.numCoc.Size = new Size(210, 28);
            this.panGroup1Field5.Controls.Add(this.numCoc);
            this.fieldsGroup1.Controls.Add(this.panGroup1Field5);
            this.chkBH.Text = "Mua bảo hiểm";
            this.chkBH.Margin = new Padding(14, 22, 12, 9);
            this.fieldsGroup1.Controls.Add(this.chkBH);
            this.panGroup1Field7 = new Panel();
            this.panGroup1Field7.Name = "panGroup1Field7";
            this.panGroup1Field7.Size = new Size(230, 67);
            this.panGroup1Field7.Margin = new Padding(5, 5, 5, 2);
            this.lblGroup1Field7 = new Label();
            this.lblGroup1Field7.Name = "lblGroup1Field7";
            this.lblGroup1Field7.Text = "Kết thúc DK";
            this.lblGroup1Field7.AutoSize = false;
            this.lblGroup1Field7.Size = new Size(215, 20);
            this.lblGroup1Field7.Location = new Point(6, 2);
            this.panGroup1Field7.Controls.Add(this.lblGroup1Field7);
            this.lblKetThuc.Location = new Point(6, 27);
            this.lblKetThuc.Size = new Size(210, 29);
            this.panGroup1Field7.Controls.Add(this.lblKetThuc);
            this.fieldsGroup1.Controls.Add(this.panGroup1Field7);
            this.panGroup1Field8 = new Panel();
            this.panGroup1Field8.Name = "panGroup1Field8";
            this.panGroup1Field8.Size = new Size(230, 67);
            this.panGroup1Field8.Margin = new Padding(5, 5, 5, 2);
            this.lblGroup1Field8 = new Label();
            this.lblGroup1Field8.Name = "lblGroup1Field8";
            this.lblGroup1Field8.Text = "Tổng dự kiến";
            this.lblGroup1Field8.AutoSize = false;
            this.lblGroup1Field8.Size = new Size(215, 20);
            this.lblGroup1Field8.Location = new Point(6, 2);
            this.panGroup1Field8.Controls.Add(this.lblGroup1Field8);
            this.lblTong.Location = new Point(6, 27);
            this.lblTong.Size = new Size(210, 29);
            this.panGroup1Field8.Controls.Add(this.lblTong);
            this.fieldsGroup1.Controls.Add(this.panGroup1Field8);
            this.grpDangKy.Controls.Add(this.fieldsGroup1);
            this.twoGroups.Controls.Add(this.grpDangKy, 1, 0);
            this.mainLayout.Controls.Add(this.twoGroups, 0, 1);
            this.grpThanhVien = new GroupBox();
            this.grpThanhVien.Name = "grpThanhVien";
            this.grpThanhVien.Text = "Danh sách người đi (bắt buộc khi mua bảo hiểm)";
            this.grpThanhVien.Dock = DockStyle.Fill;
            this.grpThanhVien.Controls.Add(this.dgvThanhVien);
            this.mainLayout.Controls.Add(this.grpThanhVien, 0, 2);
            this.actions = new FlowLayoutPanel();
            this.actions.Name = "actions";
            this.actions.Dock = DockStyle.Fill;
            this.actions.FlowDirection = FlowDirection.LeftToRight;
            this.actions.Controls.Add(this.btnDangKy);
            this.actions.Controls.Add(this.btnHuy);
            this.mainLayout.Controls.Add(this.actions, 0, 3);
            this.mainLayout.Controls.Add(this.dgv, 0, 4);
            this.footerLayout = new FlowLayoutPanel();
            this.footerLayout.Name = "footerLayout";
            this.footerLayout.Dock = DockStyle.Fill;
            this.footerLayout.FlowDirection = FlowDirection.RightToLeft;
            this.footerLayout.Padding = new Padding(6);
            this.btnDong.Size = new Size(120, 35);
            this.footerLayout.Controls.Add(this.btnDong);
            this.mainLayout.Controls.Add(this.footerLayout, 0, 5);
            this.ResumeLayout(false);
        }
    }
}
