// Giao diện WinForms tạo bằng các control và container chuẩn để Visual Studio Designer hiển thị.
// Có thể chỉnh trực tiếp vị trí, kích thước, Text trong tab Design.
using System;
using System.Drawing;
using System.Windows.Forms;

namespace QuanLyCongTyDuLich.Forms
{
    public partial class FrmDanhMuc
    {
        private System.ComponentModel.IContainer components = null;
        private TabControl tabDanhMuc;
        private DataGridView dgvPT;
        private TextBox txtPTMa;
        private TextBox txtPTTen;
        private TextBox txtPTGhiChu;
        private Button btnThemPT;
        private DataGridView dgvDB;
        private TextBox txtDBMa;
        private TextBox txtDBTen;
        private TextBox txtDBDiaChi;
        private TextBox txtDBDT;
        private Button btnThemDB;
        private DataGridView dgvHDV;
        private TextBox txtHDVMa;
        private TextBox txtHDVTen;
        private TextBox txtHDVDT;
        private NumericUpDown numLuong;
        private Button btnThemHDV;
        private DataGridView dgvDTQ;
        private TextBox txtDTQMa;
        private TextBox txtDTQTen;
        private TextBox txtDTQDiaDiem;
        private TextBox txtDTQNoiDung;
        private TextBox txtDTQYNghia;
        private Button btnThemDTQ;
        private Button btnDong;
        private TableLayoutPanel mainLayout;
        private Label lblTieuDe;
        private TabPage tabPage0;
        private TableLayoutPanel tabLayout0;
        private FlowLayoutPanel fieldsTab0;
        private Panel panTab0Field0;
        private Label lblTab0Field0;
        private Panel panTab0Field1;
        private Label lblTab0Field1;
        private Panel panTab0Field2;
        private Label lblTab0Field2;
        private Panel panTab0Field3;
        private Label lblTab0Field3;
        private TabPage tabPage1;
        private TableLayoutPanel tabLayout1;
        private FlowLayoutPanel fieldsTab1;
        private Panel panTab1Field0;
        private Label lblTab1Field0;
        private Panel panTab1Field1;
        private Label lblTab1Field1;
        private Panel panTab1Field2;
        private Label lblTab1Field2;
        private Panel panTab1Field3;
        private Label lblTab1Field3;
        private Panel panTab1Field4;
        private Label lblTab1Field4;
        private TabPage tabPage2;
        private TableLayoutPanel tabLayout2;
        private FlowLayoutPanel fieldsTab2;
        private Panel panTab2Field0;
        private Label lblTab2Field0;
        private Panel panTab2Field1;
        private Label lblTab2Field1;
        private Panel panTab2Field2;
        private Label lblTab2Field2;
        private Panel panTab2Field3;
        private Label lblTab2Field3;
        private Panel panTab2Field4;
        private Label lblTab2Field4;
        private TabPage tabPage3;
        private TableLayoutPanel tabLayout3;
        private FlowLayoutPanel fieldsTab3;
        private Panel panTab3Field0;
        private Label lblTab3Field0;
        private Panel panTab3Field1;
        private Label lblTab3Field1;
        private Panel panTab3Field2;
        private Label lblTab3Field2;
        private Panel panTab3Field3;
        private Label lblTab3Field3;
        private Panel panTab3Field4;
        private Label lblTab3Field4;
        private Panel panTab3Field5;
        private Label lblTab3Field5;
        private FlowLayoutPanel footerLayout;

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null) this.components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.tabDanhMuc = new TabControl();
            this.tabDanhMuc.Name = "tabDanhMuc";
            this.dgvPT = new DataGridView();
            this.dgvPT.Name = "dgvPT";
            this.dgvPT.Dock = DockStyle.Fill;
            this.dgvPT.BackgroundColor = Color.White;
            this.dgvPT.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
            this.dgvPT.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvPT.MultiSelect = false;
            this.dgvPT.RowHeadersVisible = false;
            this.dgvPT.AllowUserToAddRows = false;
            this.dgvPT.AllowUserToDeleteRows = false;
            this.dgvPT.ReadOnly = true;
            this.txtPTMa = new TextBox();
            this.txtPTMa.Name = "txtPTMa";
            this.txtPTMa.Size = new Size(205, 29);
            this.txtPTTen = new TextBox();
            this.txtPTTen.Name = "txtPTTen";
            this.txtPTTen.Size = new Size(205, 29);
            this.txtPTGhiChu = new TextBox();
            this.txtPTGhiChu.Name = "txtPTGhiChu";
            this.txtPTGhiChu.Size = new Size(205, 29);
            this.btnThemPT = new Button();
            this.btnThemPT.Name = "btnThemPT";
            this.btnThemPT.Text = "Thêm";
            this.btnThemPT.Size = new Size(190, 36);
            this.btnThemPT.FlatStyle = FlatStyle.Standard;
            this.dgvDB = new DataGridView();
            this.dgvDB.Name = "dgvDB";
            this.dgvDB.Dock = DockStyle.Fill;
            this.dgvDB.BackgroundColor = Color.White;
            this.dgvDB.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
            this.dgvDB.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvDB.MultiSelect = false;
            this.dgvDB.RowHeadersVisible = false;
            this.dgvDB.AllowUserToAddRows = false;
            this.dgvDB.AllowUserToDeleteRows = false;
            this.dgvDB.ReadOnly = true;
            this.txtDBMa = new TextBox();
            this.txtDBMa.Name = "txtDBMa";
            this.txtDBMa.Size = new Size(205, 29);
            this.txtDBTen = new TextBox();
            this.txtDBTen.Name = "txtDBTen";
            this.txtDBTen.Size = new Size(205, 29);
            this.txtDBDiaChi = new TextBox();
            this.txtDBDiaChi.Name = "txtDBDiaChi";
            this.txtDBDiaChi.Size = new Size(205, 29);
            this.txtDBDT = new TextBox();
            this.txtDBDT.Name = "txtDBDT";
            this.txtDBDT.Size = new Size(205, 29);
            this.btnThemDB = new Button();
            this.btnThemDB.Name = "btnThemDB";
            this.btnThemDB.Text = "Thêm";
            this.btnThemDB.Size = new Size(190, 36);
            this.btnThemDB.FlatStyle = FlatStyle.Standard;
            this.dgvHDV = new DataGridView();
            this.dgvHDV.Name = "dgvHDV";
            this.dgvHDV.Dock = DockStyle.Fill;
            this.dgvHDV.BackgroundColor = Color.White;
            this.dgvHDV.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
            this.dgvHDV.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvHDV.MultiSelect = false;
            this.dgvHDV.RowHeadersVisible = false;
            this.dgvHDV.AllowUserToAddRows = false;
            this.dgvHDV.AllowUserToDeleteRows = false;
            this.dgvHDV.ReadOnly = true;
            this.txtHDVMa = new TextBox();
            this.txtHDVMa.Name = "txtHDVMa";
            this.txtHDVMa.Size = new Size(205, 29);
            this.txtHDVTen = new TextBox();
            this.txtHDVTen.Name = "txtHDVTen";
            this.txtHDVTen.Size = new Size(205, 29);
            this.txtHDVDT = new TextBox();
            this.txtHDVDT.Name = "txtHDVDT";
            this.txtHDVDT.Size = new Size(205, 29);
            this.numLuong = new NumericUpDown();
            this.numLuong.Name = "numLuong";
            this.numLuong.Maximum = 100000000000M;
            this.numLuong.Minimum = 0;
            this.numLuong.Size = new Size(205, 28);
            this.btnThemHDV = new Button();
            this.btnThemHDV.Name = "btnThemHDV";
            this.btnThemHDV.Text = "Thêm";
            this.btnThemHDV.Size = new Size(190, 36);
            this.btnThemHDV.FlatStyle = FlatStyle.Standard;
            this.dgvDTQ = new DataGridView();
            this.dgvDTQ.Name = "dgvDTQ";
            this.dgvDTQ.Dock = DockStyle.Fill;
            this.dgvDTQ.BackgroundColor = Color.White;
            this.dgvDTQ.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
            this.dgvDTQ.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvDTQ.MultiSelect = false;
            this.dgvDTQ.RowHeadersVisible = false;
            this.dgvDTQ.AllowUserToAddRows = false;
            this.dgvDTQ.AllowUserToDeleteRows = false;
            this.dgvDTQ.ReadOnly = true;
            this.txtDTQMa = new TextBox();
            this.txtDTQMa.Name = "txtDTQMa";
            this.txtDTQMa.Size = new Size(205, 29);
            this.txtDTQTen = new TextBox();
            this.txtDTQTen.Name = "txtDTQTen";
            this.txtDTQTen.Size = new Size(205, 29);
            this.txtDTQDiaDiem = new TextBox();
            this.txtDTQDiaDiem.Name = "txtDTQDiaDiem";
            this.txtDTQDiaDiem.Size = new Size(205, 29);
            this.txtDTQNoiDung = new TextBox();
            this.txtDTQNoiDung.Name = "txtDTQNoiDung";
            this.txtDTQNoiDung.Size = new Size(205, 29);
            this.txtDTQYNghia = new TextBox();
            this.txtDTQYNghia.Name = "txtDTQYNghia";
            this.txtDTQYNghia.Size = new Size(205, 29);
            this.btnThemDTQ = new Button();
            this.btnThemDTQ.Name = "btnThemDTQ";
            this.btnThemDTQ.Text = "Thêm";
            this.btnThemDTQ.Size = new Size(190, 36);
            this.btnThemDTQ.FlatStyle = FlatStyle.Standard;
            this.btnDong = new Button();
            this.btnDong.Name = "btnDong";
            this.btnDong.Text = "Đóng";
            this.btnDong.Size = new Size(190, 36);
            this.btnDong.FlatStyle = FlatStyle.Standard;
            this.btnThemPT.Click += new EventHandler(this.btnThemPT_Click);
            this.btnThemDB.Click += new EventHandler(this.btnThemDB_Click);
            this.btnThemHDV.Click += new EventHandler(this.btnThemHDV_Click);
            this.btnThemDTQ.Click += new EventHandler(this.btnThemDTQ_Click);
            this.btnDong.Click += new EventHandler(this.btnDong_Click);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.ClientSize = new Size(1120, 760);
            this.MinimumSize = new Size(800, 600);
            this.StartPosition = FormStartPosition.CenterScreen;
            this.Font = new Font("Segoe UI", 9.5f);
            this.Text = "Quản lý danh mục";
            this.Load += new EventHandler(this.FrmDanhMuc_Load);
            this.mainLayout = new TableLayoutPanel();
            this.mainLayout.Name = "mainLayout";
            this.mainLayout.Dock = DockStyle.Fill;
            this.mainLayout.Padding = new Padding(12);
            this.mainLayout.ColumnCount = 1;
            this.mainLayout.RowCount = 3;
            this.mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 70F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 55F));
            this.Controls.Add(this.mainLayout);
            this.lblTieuDe = new Label();
            this.lblTieuDe.Name = "lblTieuDe";
            this.lblTieuDe.Text = "Quản lý danh mục";
            this.lblTieuDe.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
            this.lblTieuDe.ForeColor = Color.FromArgb(33, 65, 94);
            this.lblTieuDe.Dock = DockStyle.Fill;
            this.lblTieuDe.TextAlign = ContentAlignment.MiddleCenter;
            this.mainLayout.Controls.Add(this.lblTieuDe, 0, 0);
            this.tabDanhMuc.Dock = DockStyle.Fill;
            this.tabPage0 = new TabPage();
            this.tabPage0.Name = "tabPage0";
            this.tabPage0.Text = "Phương tiện";
            this.tabPage0.Padding = new Padding(8);
            this.tabLayout0 = new TableLayoutPanel();
            this.tabLayout0.Name = "tabLayout0";
            this.tabLayout0.Dock = DockStyle.Fill;
            this.tabLayout0.ColumnCount = 1;
            this.tabLayout0.RowCount = 2;
            this.tabLayout0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.tabLayout0.RowStyles.Add(new RowStyle(SizeType.Percent, 64F));
            this.tabLayout0.RowStyles.Add(new RowStyle(SizeType.Percent, 36F));
            this.fieldsTab0 = new FlowLayoutPanel();
            this.fieldsTab0.Name = "fieldsTab0";
            this.fieldsTab0.Dock = DockStyle.Fill;
            this.fieldsTab0.AutoScroll = true;
            this.fieldsTab0.WrapContents = true;
            this.fieldsTab0.Padding = new Padding(6);
            this.fieldsTab0.FlowDirection = FlowDirection.LeftToRight;
            this.panTab0Field0 = new Panel();
            this.panTab0Field0.Name = "panTab0Field0";
            this.panTab0Field0.Size = new Size(230, 67);
            this.panTab0Field0.Margin = new Padding(5, 5, 5, 2);
            this.lblTab0Field0 = new Label();
            this.lblTab0Field0.Name = "lblTab0Field0";
            this.lblTab0Field0.Text = "Mã PT";
            this.lblTab0Field0.AutoSize = false;
            this.lblTab0Field0.Size = new Size(215, 20);
            this.lblTab0Field0.Location = new Point(6, 2);
            this.panTab0Field0.Controls.Add(this.lblTab0Field0);
            this.txtPTMa.Location = new Point(6, 27);
            this.txtPTMa.Size = new Size(210, 28);
            this.panTab0Field0.Controls.Add(this.txtPTMa);
            this.fieldsTab0.Controls.Add(this.panTab0Field0);
            this.panTab0Field1 = new Panel();
            this.panTab0Field1.Name = "panTab0Field1";
            this.panTab0Field1.Size = new Size(230, 67);
            this.panTab0Field1.Margin = new Padding(5, 5, 5, 2);
            this.lblTab0Field1 = new Label();
            this.lblTab0Field1.Name = "lblTab0Field1";
            this.lblTab0Field1.Text = "Tên PT";
            this.lblTab0Field1.AutoSize = false;
            this.lblTab0Field1.Size = new Size(215, 20);
            this.lblTab0Field1.Location = new Point(6, 2);
            this.panTab0Field1.Controls.Add(this.lblTab0Field1);
            this.txtPTTen.Location = new Point(6, 27);
            this.txtPTTen.Size = new Size(210, 28);
            this.panTab0Field1.Controls.Add(this.txtPTTen);
            this.fieldsTab0.Controls.Add(this.panTab0Field1);
            this.panTab0Field2 = new Panel();
            this.panTab0Field2.Name = "panTab0Field2";
            this.panTab0Field2.Size = new Size(230, 67);
            this.panTab0Field2.Margin = new Padding(5, 5, 5, 2);
            this.lblTab0Field2 = new Label();
            this.lblTab0Field2.Name = "lblTab0Field2";
            this.lblTab0Field2.Text = "Ghi chú";
            this.lblTab0Field2.AutoSize = false;
            this.lblTab0Field2.Size = new Size(215, 20);
            this.lblTab0Field2.Location = new Point(6, 2);
            this.panTab0Field2.Controls.Add(this.lblTab0Field2);
            this.txtPTGhiChu.Location = new Point(6, 27);
            this.txtPTGhiChu.Size = new Size(210, 28);
            this.panTab0Field2.Controls.Add(this.txtPTGhiChu);
            this.fieldsTab0.Controls.Add(this.panTab0Field2);
            this.panTab0Field3 = new Panel();
            this.panTab0Field3.Name = "panTab0Field3";
            this.panTab0Field3.Size = new Size(230, 67);
            this.panTab0Field3.Margin = new Padding(5, 5, 5, 2);
            this.lblTab0Field3 = new Label();
            this.lblTab0Field3.Name = "lblTab0Field3";
            this.lblTab0Field3.Text = "Thêm";
            this.lblTab0Field3.AutoSize = false;
            this.lblTab0Field3.Size = new Size(215, 20);
            this.lblTab0Field3.Location = new Point(6, 2);
            this.panTab0Field3.Controls.Add(this.lblTab0Field3);
            this.btnThemPT.Location = new Point(6, 27);
            this.btnThemPT.Size = new Size(210, 34);
            this.panTab0Field3.Controls.Add(this.btnThemPT);
            this.fieldsTab0.Controls.Add(this.panTab0Field3);
            this.tabLayout0.Controls.Add(this.dgvPT, 0, 0);
            this.tabLayout0.Controls.Add(this.fieldsTab0, 0, 1);
            this.tabPage0.Controls.Add(this.tabLayout0);
            this.tabDanhMuc.Controls.Add(this.tabPage0);
            this.tabPage1 = new TabPage();
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Text = "Điểm bán vé";
            this.tabPage1.Padding = new Padding(8);
            this.tabLayout1 = new TableLayoutPanel();
            this.tabLayout1.Name = "tabLayout1";
            this.tabLayout1.Dock = DockStyle.Fill;
            this.tabLayout1.ColumnCount = 1;
            this.tabLayout1.RowCount = 2;
            this.tabLayout1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.tabLayout1.RowStyles.Add(new RowStyle(SizeType.Percent, 64F));
            this.tabLayout1.RowStyles.Add(new RowStyle(SizeType.Percent, 36F));
            this.fieldsTab1 = new FlowLayoutPanel();
            this.fieldsTab1.Name = "fieldsTab1";
            this.fieldsTab1.Dock = DockStyle.Fill;
            this.fieldsTab1.AutoScroll = true;
            this.fieldsTab1.WrapContents = true;
            this.fieldsTab1.Padding = new Padding(6);
            this.fieldsTab1.FlowDirection = FlowDirection.LeftToRight;
            this.panTab1Field0 = new Panel();
            this.panTab1Field0.Name = "panTab1Field0";
            this.panTab1Field0.Size = new Size(230, 67);
            this.panTab1Field0.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field0 = new Label();
            this.lblTab1Field0.Name = "lblTab1Field0";
            this.lblTab1Field0.Text = "Mã điểm bán";
            this.lblTab1Field0.AutoSize = false;
            this.lblTab1Field0.Size = new Size(215, 20);
            this.lblTab1Field0.Location = new Point(6, 2);
            this.panTab1Field0.Controls.Add(this.lblTab1Field0);
            this.txtDBMa.Location = new Point(6, 27);
            this.txtDBMa.Size = new Size(210, 28);
            this.panTab1Field0.Controls.Add(this.txtDBMa);
            this.fieldsTab1.Controls.Add(this.panTab1Field0);
            this.panTab1Field1 = new Panel();
            this.panTab1Field1.Name = "panTab1Field1";
            this.panTab1Field1.Size = new Size(230, 67);
            this.panTab1Field1.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field1 = new Label();
            this.lblTab1Field1.Name = "lblTab1Field1";
            this.lblTab1Field1.Text = "Tên điểm bán";
            this.lblTab1Field1.AutoSize = false;
            this.lblTab1Field1.Size = new Size(215, 20);
            this.lblTab1Field1.Location = new Point(6, 2);
            this.panTab1Field1.Controls.Add(this.lblTab1Field1);
            this.txtDBTen.Location = new Point(6, 27);
            this.txtDBTen.Size = new Size(210, 28);
            this.panTab1Field1.Controls.Add(this.txtDBTen);
            this.fieldsTab1.Controls.Add(this.panTab1Field1);
            this.panTab1Field2 = new Panel();
            this.panTab1Field2.Name = "panTab1Field2";
            this.panTab1Field2.Size = new Size(230, 67);
            this.panTab1Field2.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field2 = new Label();
            this.lblTab1Field2.Name = "lblTab1Field2";
            this.lblTab1Field2.Text = "Địa chỉ";
            this.lblTab1Field2.AutoSize = false;
            this.lblTab1Field2.Size = new Size(215, 20);
            this.lblTab1Field2.Location = new Point(6, 2);
            this.panTab1Field2.Controls.Add(this.lblTab1Field2);
            this.txtDBDiaChi.Location = new Point(6, 27);
            this.txtDBDiaChi.Size = new Size(210, 28);
            this.panTab1Field2.Controls.Add(this.txtDBDiaChi);
            this.fieldsTab1.Controls.Add(this.panTab1Field2);
            this.panTab1Field3 = new Panel();
            this.panTab1Field3.Name = "panTab1Field3";
            this.panTab1Field3.Size = new Size(230, 67);
            this.panTab1Field3.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field3 = new Label();
            this.lblTab1Field3.Name = "lblTab1Field3";
            this.lblTab1Field3.Text = "Điện thoại";
            this.lblTab1Field3.AutoSize = false;
            this.lblTab1Field3.Size = new Size(215, 20);
            this.lblTab1Field3.Location = new Point(6, 2);
            this.panTab1Field3.Controls.Add(this.lblTab1Field3);
            this.txtDBDT.Location = new Point(6, 27);
            this.txtDBDT.Size = new Size(210, 28);
            this.panTab1Field3.Controls.Add(this.txtDBDT);
            this.fieldsTab1.Controls.Add(this.panTab1Field3);
            this.panTab1Field4 = new Panel();
            this.panTab1Field4.Name = "panTab1Field4";
            this.panTab1Field4.Size = new Size(230, 67);
            this.panTab1Field4.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field4 = new Label();
            this.lblTab1Field4.Name = "lblTab1Field4";
            this.lblTab1Field4.Text = "Thêm";
            this.lblTab1Field4.AutoSize = false;
            this.lblTab1Field4.Size = new Size(215, 20);
            this.lblTab1Field4.Location = new Point(6, 2);
            this.panTab1Field4.Controls.Add(this.lblTab1Field4);
            this.btnThemDB.Location = new Point(6, 27);
            this.btnThemDB.Size = new Size(210, 34);
            this.panTab1Field4.Controls.Add(this.btnThemDB);
            this.fieldsTab1.Controls.Add(this.panTab1Field4);
            this.tabLayout1.Controls.Add(this.dgvDB, 0, 0);
            this.tabLayout1.Controls.Add(this.fieldsTab1, 0, 1);
            this.tabPage1.Controls.Add(this.tabLayout1);
            this.tabDanhMuc.Controls.Add(this.tabPage1);
            this.tabPage2 = new TabPage();
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Text = "Hướng dẫn viên";
            this.tabPage2.Padding = new Padding(8);
            this.tabLayout2 = new TableLayoutPanel();
            this.tabLayout2.Name = "tabLayout2";
            this.tabLayout2.Dock = DockStyle.Fill;
            this.tabLayout2.ColumnCount = 1;
            this.tabLayout2.RowCount = 2;
            this.tabLayout2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.tabLayout2.RowStyles.Add(new RowStyle(SizeType.Percent, 64F));
            this.tabLayout2.RowStyles.Add(new RowStyle(SizeType.Percent, 36F));
            this.fieldsTab2 = new FlowLayoutPanel();
            this.fieldsTab2.Name = "fieldsTab2";
            this.fieldsTab2.Dock = DockStyle.Fill;
            this.fieldsTab2.AutoScroll = true;
            this.fieldsTab2.WrapContents = true;
            this.fieldsTab2.Padding = new Padding(6);
            this.fieldsTab2.FlowDirection = FlowDirection.LeftToRight;
            this.panTab2Field0 = new Panel();
            this.panTab2Field0.Name = "panTab2Field0";
            this.panTab2Field0.Size = new Size(230, 67);
            this.panTab2Field0.Margin = new Padding(5, 5, 5, 2);
            this.lblTab2Field0 = new Label();
            this.lblTab2Field0.Name = "lblTab2Field0";
            this.lblTab2Field0.Text = "Mã HDV";
            this.lblTab2Field0.AutoSize = false;
            this.lblTab2Field0.Size = new Size(215, 20);
            this.lblTab2Field0.Location = new Point(6, 2);
            this.panTab2Field0.Controls.Add(this.lblTab2Field0);
            this.txtHDVMa.Location = new Point(6, 27);
            this.txtHDVMa.Size = new Size(210, 28);
            this.panTab2Field0.Controls.Add(this.txtHDVMa);
            this.fieldsTab2.Controls.Add(this.panTab2Field0);
            this.panTab2Field1 = new Panel();
            this.panTab2Field1.Name = "panTab2Field1";
            this.panTab2Field1.Size = new Size(230, 67);
            this.panTab2Field1.Margin = new Padding(5, 5, 5, 2);
            this.lblTab2Field1 = new Label();
            this.lblTab2Field1.Name = "lblTab2Field1";
            this.lblTab2Field1.Text = "Họ tên";
            this.lblTab2Field1.AutoSize = false;
            this.lblTab2Field1.Size = new Size(215, 20);
            this.lblTab2Field1.Location = new Point(6, 2);
            this.panTab2Field1.Controls.Add(this.lblTab2Field1);
            this.txtHDVTen.Location = new Point(6, 27);
            this.txtHDVTen.Size = new Size(210, 28);
            this.panTab2Field1.Controls.Add(this.txtHDVTen);
            this.fieldsTab2.Controls.Add(this.panTab2Field1);
            this.panTab2Field2 = new Panel();
            this.panTab2Field2.Name = "panTab2Field2";
            this.panTab2Field2.Size = new Size(230, 67);
            this.panTab2Field2.Margin = new Padding(5, 5, 5, 2);
            this.lblTab2Field2 = new Label();
            this.lblTab2Field2.Name = "lblTab2Field2";
            this.lblTab2Field2.Text = "Điện thoại";
            this.lblTab2Field2.AutoSize = false;
            this.lblTab2Field2.Size = new Size(215, 20);
            this.lblTab2Field2.Location = new Point(6, 2);
            this.panTab2Field2.Controls.Add(this.lblTab2Field2);
            this.txtHDVDT.Location = new Point(6, 27);
            this.txtHDVDT.Size = new Size(210, 28);
            this.panTab2Field2.Controls.Add(this.txtHDVDT);
            this.fieldsTab2.Controls.Add(this.panTab2Field2);
            this.panTab2Field3 = new Panel();
            this.panTab2Field3.Name = "panTab2Field3";
            this.panTab2Field3.Size = new Size(230, 67);
            this.panTab2Field3.Margin = new Padding(5, 5, 5, 2);
            this.lblTab2Field3 = new Label();
            this.lblTab2Field3.Name = "lblTab2Field3";
            this.lblTab2Field3.Text = "Lương căn bản";
            this.lblTab2Field3.AutoSize = false;
            this.lblTab2Field3.Size = new Size(215, 20);
            this.lblTab2Field3.Location = new Point(6, 2);
            this.panTab2Field3.Controls.Add(this.lblTab2Field3);
            this.numLuong.Location = new Point(6, 27);
            this.numLuong.Size = new Size(210, 28);
            this.panTab2Field3.Controls.Add(this.numLuong);
            this.fieldsTab2.Controls.Add(this.panTab2Field3);
            this.panTab2Field4 = new Panel();
            this.panTab2Field4.Name = "panTab2Field4";
            this.panTab2Field4.Size = new Size(230, 67);
            this.panTab2Field4.Margin = new Padding(5, 5, 5, 2);
            this.lblTab2Field4 = new Label();
            this.lblTab2Field4.Name = "lblTab2Field4";
            this.lblTab2Field4.Text = "Thêm";
            this.lblTab2Field4.AutoSize = false;
            this.lblTab2Field4.Size = new Size(215, 20);
            this.lblTab2Field4.Location = new Point(6, 2);
            this.panTab2Field4.Controls.Add(this.lblTab2Field4);
            this.btnThemHDV.Location = new Point(6, 27);
            this.btnThemHDV.Size = new Size(210, 34);
            this.panTab2Field4.Controls.Add(this.btnThemHDV);
            this.fieldsTab2.Controls.Add(this.panTab2Field4);
            this.tabLayout2.Controls.Add(this.dgvHDV, 0, 0);
            this.tabLayout2.Controls.Add(this.fieldsTab2, 0, 1);
            this.tabPage2.Controls.Add(this.tabLayout2);
            this.tabDanhMuc.Controls.Add(this.tabPage2);
            this.tabPage3 = new TabPage();
            this.tabPage3.Name = "tabPage3";
            this.tabPage3.Text = "Điểm tham quan";
            this.tabPage3.Padding = new Padding(8);
            this.tabLayout3 = new TableLayoutPanel();
            this.tabLayout3.Name = "tabLayout3";
            this.tabLayout3.Dock = DockStyle.Fill;
            this.tabLayout3.ColumnCount = 1;
            this.tabLayout3.RowCount = 2;
            this.tabLayout3.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.tabLayout3.RowStyles.Add(new RowStyle(SizeType.Percent, 64F));
            this.tabLayout3.RowStyles.Add(new RowStyle(SizeType.Percent, 36F));
            this.fieldsTab3 = new FlowLayoutPanel();
            this.fieldsTab3.Name = "fieldsTab3";
            this.fieldsTab3.Dock = DockStyle.Fill;
            this.fieldsTab3.AutoScroll = true;
            this.fieldsTab3.WrapContents = true;
            this.fieldsTab3.Padding = new Padding(6);
            this.fieldsTab3.FlowDirection = FlowDirection.LeftToRight;
            this.panTab3Field0 = new Panel();
            this.panTab3Field0.Name = "panTab3Field0";
            this.panTab3Field0.Size = new Size(230, 67);
            this.panTab3Field0.Margin = new Padding(5, 5, 5, 2);
            this.lblTab3Field0 = new Label();
            this.lblTab3Field0.Name = "lblTab3Field0";
            this.lblTab3Field0.Text = "Mã điểm TQ";
            this.lblTab3Field0.AutoSize = false;
            this.lblTab3Field0.Size = new Size(215, 20);
            this.lblTab3Field0.Location = new Point(6, 2);
            this.panTab3Field0.Controls.Add(this.lblTab3Field0);
            this.txtDTQMa.Location = new Point(6, 27);
            this.txtDTQMa.Size = new Size(210, 28);
            this.panTab3Field0.Controls.Add(this.txtDTQMa);
            this.fieldsTab3.Controls.Add(this.panTab3Field0);
            this.panTab3Field1 = new Panel();
            this.panTab3Field1.Name = "panTab3Field1";
            this.panTab3Field1.Size = new Size(230, 67);
            this.panTab3Field1.Margin = new Padding(5, 5, 5, 2);
            this.lblTab3Field1 = new Label();
            this.lblTab3Field1.Name = "lblTab3Field1";
            this.lblTab3Field1.Text = "Tên điểm TQ";
            this.lblTab3Field1.AutoSize = false;
            this.lblTab3Field1.Size = new Size(215, 20);
            this.lblTab3Field1.Location = new Point(6, 2);
            this.panTab3Field1.Controls.Add(this.lblTab3Field1);
            this.txtDTQTen.Location = new Point(6, 27);
            this.txtDTQTen.Size = new Size(210, 28);
            this.panTab3Field1.Controls.Add(this.txtDTQTen);
            this.fieldsTab3.Controls.Add(this.panTab3Field1);
            this.panTab3Field2 = new Panel();
            this.panTab3Field2.Name = "panTab3Field2";
            this.panTab3Field2.Size = new Size(230, 67);
            this.panTab3Field2.Margin = new Padding(5, 5, 5, 2);
            this.lblTab3Field2 = new Label();
            this.lblTab3Field2.Name = "lblTab3Field2";
            this.lblTab3Field2.Text = "Địa điểm";
            this.lblTab3Field2.AutoSize = false;
            this.lblTab3Field2.Size = new Size(215, 20);
            this.lblTab3Field2.Location = new Point(6, 2);
            this.panTab3Field2.Controls.Add(this.lblTab3Field2);
            this.txtDTQDiaDiem.Location = new Point(6, 27);
            this.txtDTQDiaDiem.Size = new Size(210, 28);
            this.panTab3Field2.Controls.Add(this.txtDTQDiaDiem);
            this.fieldsTab3.Controls.Add(this.panTab3Field2);
            this.panTab3Field3 = new Panel();
            this.panTab3Field3.Name = "panTab3Field3";
            this.panTab3Field3.Size = new Size(230, 67);
            this.panTab3Field3.Margin = new Padding(5, 5, 5, 2);
            this.lblTab3Field3 = new Label();
            this.lblTab3Field3.Name = "lblTab3Field3";
            this.lblTab3Field3.Text = "Nội dung";
            this.lblTab3Field3.AutoSize = false;
            this.lblTab3Field3.Size = new Size(215, 20);
            this.lblTab3Field3.Location = new Point(6, 2);
            this.panTab3Field3.Controls.Add(this.lblTab3Field3);
            this.txtDTQNoiDung.Location = new Point(6, 27);
            this.txtDTQNoiDung.Size = new Size(210, 28);
            this.panTab3Field3.Controls.Add(this.txtDTQNoiDung);
            this.fieldsTab3.Controls.Add(this.panTab3Field3);
            this.panTab3Field4 = new Panel();
            this.panTab3Field4.Name = "panTab3Field4";
            this.panTab3Field4.Size = new Size(230, 67);
            this.panTab3Field4.Margin = new Padding(5, 5, 5, 2);
            this.lblTab3Field4 = new Label();
            this.lblTab3Field4.Name = "lblTab3Field4";
            this.lblTab3Field4.Text = "Ý nghĩa";
            this.lblTab3Field4.AutoSize = false;
            this.lblTab3Field4.Size = new Size(215, 20);
            this.lblTab3Field4.Location = new Point(6, 2);
            this.panTab3Field4.Controls.Add(this.lblTab3Field4);
            this.txtDTQYNghia.Location = new Point(6, 27);
            this.txtDTQYNghia.Size = new Size(210, 28);
            this.panTab3Field4.Controls.Add(this.txtDTQYNghia);
            this.fieldsTab3.Controls.Add(this.panTab3Field4);
            this.panTab3Field5 = new Panel();
            this.panTab3Field5.Name = "panTab3Field5";
            this.panTab3Field5.Size = new Size(230, 67);
            this.panTab3Field5.Margin = new Padding(5, 5, 5, 2);
            this.lblTab3Field5 = new Label();
            this.lblTab3Field5.Name = "lblTab3Field5";
            this.lblTab3Field5.Text = "Thêm";
            this.lblTab3Field5.AutoSize = false;
            this.lblTab3Field5.Size = new Size(215, 20);
            this.lblTab3Field5.Location = new Point(6, 2);
            this.panTab3Field5.Controls.Add(this.lblTab3Field5);
            this.btnThemDTQ.Location = new Point(6, 27);
            this.btnThemDTQ.Size = new Size(210, 34);
            this.panTab3Field5.Controls.Add(this.btnThemDTQ);
            this.fieldsTab3.Controls.Add(this.panTab3Field5);
            this.tabLayout3.Controls.Add(this.dgvDTQ, 0, 0);
            this.tabLayout3.Controls.Add(this.fieldsTab3, 0, 1);
            this.tabPage3.Controls.Add(this.tabLayout3);
            this.tabDanhMuc.Controls.Add(this.tabPage3);
            this.mainLayout.Controls.Add(this.tabDanhMuc, 0, 1);
            this.footerLayout = new FlowLayoutPanel();
            this.footerLayout.Name = "footerLayout";
            this.footerLayout.Dock = DockStyle.Fill;
            this.footerLayout.FlowDirection = FlowDirection.RightToLeft;
            this.footerLayout.Padding = new Padding(6);
            this.btnDong.Size = new Size(120, 35);
            this.footerLayout.Controls.Add(this.btnDong);
            this.mainLayout.Controls.Add(this.footerLayout, 0, 2);
            this.ResumeLayout(false);
        }
    }
}
