// Giao diện WinForms tạo bằng các control và container chuẩn để Visual Studio Designer hiển thị.
// Có thể chỉnh trực tiếp vị trí, kích thước, Text trong tab Design.
using System;
using System.Drawing;
using System.Windows.Forms;

namespace QuanLyCongTyDuLich.Forms
{
    public partial class FrmKetThucKhaoSat
    {
        private System.ComponentModel.IContainer components = null;
        private TabControl tabKT;
        private DataGridView dgvDoan;
        private TextBox txtSoTT;
        private TextBox txtSoDK;
        private DateTimePicker dtTT;
        private NumericUpDown numTien;
        private TextBox txtGhiChu;
        private Button btnThanhToan;
        private ComboBox cboLoaiKS;
        private ComboBox cboDangKy;
        private TextBox txtMaKS;
        private DateTimePicker dtGui;
        private Button btnGui;
        private DataGridView dgvKS;
        private TextBox txtKSChon;
        private DateTimePicker dtPH;
        private NumericUpDown numDiem;
        private TextBox txtGopY;
        private Button btnGhiPH;
        private Button btnDong;
        private TableLayoutPanel mainLayout;
        private Label lblTieuDe;
        private TabPage tabPage0;
        private TableLayoutPanel tabLayout0;
        private FlowLayoutPanel fieldsTab0;
        private Panel panTab0Field0;
        private Label lblTab0Field0;
        private Panel panTab0Field1;
        private Label lblTab0Field1;
        private Panel panTab0Field2;
        private Label lblTab0Field2;
        private Panel panTab0Field3;
        private Label lblTab0Field3;
        private Panel panTab0Field4;
        private Label lblTab0Field4;
        private Panel panTab0Field5;
        private Label lblTab0Field5;
        private TabPage tabPage1;
        private TableLayoutPanel tabLayout1;
        private FlowLayoutPanel fieldsTab1;
        private Panel panTab1Field0;
        private Label lblTab1Field0;
        private Panel panTab1Field1;
        private Label lblTab1Field1;
        private Panel panTab1Field2;
        private Label lblTab1Field2;
        private Panel panTab1Field3;
        private Label lblTab1Field3;
        private Panel panTab1Field4;
        private Label lblTab1Field4;
        private Panel panTab1Field5;
        private Label lblTab1Field5;
        private Panel panTab1Field6;
        private Label lblTab1Field6;
        private Panel panTab1Field7;
        private Label lblTab1Field7;
        private Panel panTab1Field8;
        private Label lblTab1Field8;
        private Panel panTab1Field9;
        private Label lblTab1Field9;
        private FlowLayoutPanel footerLayout;

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null) this.components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.tabKT = new TabControl();
            this.tabKT.Name = "tabKT";
            this.dgvDoan = new DataGridView();
            this.dgvDoan.Name = "dgvDoan";
            this.dgvDoan.Dock = DockStyle.Fill;
            this.dgvDoan.BackgroundColor = Color.White;
            this.dgvDoan.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
            this.dgvDoan.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvDoan.MultiSelect = false;
            this.dgvDoan.RowHeadersVisible = false;
            this.dgvDoan.AllowUserToAddRows = false;
            this.dgvDoan.AllowUserToDeleteRows = false;
            this.dgvDoan.ReadOnly = true;
            this.txtSoTT = new TextBox();
            this.txtSoTT.Name = "txtSoTT";
            this.txtSoTT.Size = new Size(205, 29);
            this.txtSoDK = new TextBox();
            this.txtSoDK.Name = "txtSoDK";
            this.txtSoDK.Size = new Size(205, 29);
            this.txtSoDK.ReadOnly = true;
            this.dtTT = new DateTimePicker();
            this.dtTT.Name = "dtTT";
            this.dtTT.Format = DateTimePickerFormat.Short;
            this.dtTT.Size = new Size(205, 30);
            this.numTien = new NumericUpDown();
            this.numTien.Name = "numTien";
            this.numTien.Maximum = 100000000000M;
            this.numTien.Minimum = 0;
            this.numTien.Size = new Size(205, 28);
            this.txtGhiChu = new TextBox();
            this.txtGhiChu.Name = "txtGhiChu";
            this.txtGhiChu.Size = new Size(205, 29);
            this.btnThanhToan = new Button();
            this.btnThanhToan.Name = "btnThanhToan";
            this.btnThanhToan.Text = "Ghi nhận thanh toán";
            this.btnThanhToan.Size = new Size(190, 36);
            this.btnThanhToan.FlatStyle = FlatStyle.Standard;
            this.cboLoaiKS = new ComboBox();
            this.cboLoaiKS.Name = "cboLoaiKS";
            this.cboLoaiKS.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboDangKy = new ComboBox();
            this.cboDangKy.Name = "cboDangKy";
            this.cboDangKy.DropDownStyle = ComboBoxStyle.DropDownList;
            this.txtMaKS = new TextBox();
            this.txtMaKS.Name = "txtMaKS";
            this.txtMaKS.Size = new Size(205, 29);
            this.dtGui = new DateTimePicker();
            this.dtGui.Name = "dtGui";
            this.dtGui.Format = DateTimePickerFormat.Short;
            this.dtGui.Size = new Size(205, 30);
            this.btnGui = new Button();
            this.btnGui.Name = "btnGui";
            this.btnGui.Text = "Gửi phiếu khảo sát";
            this.btnGui.Size = new Size(190, 36);
            this.btnGui.FlatStyle = FlatStyle.Standard;
            this.dgvKS = new DataGridView();
            this.dgvKS.Name = "dgvKS";
            this.dgvKS.Dock = DockStyle.Fill;
            this.dgvKS.BackgroundColor = Color.White;
            this.dgvKS.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
            this.dgvKS.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvKS.MultiSelect = false;
            this.dgvKS.RowHeadersVisible = false;
            this.dgvKS.AllowUserToAddRows = false;
            this.dgvKS.AllowUserToDeleteRows = false;
            this.dgvKS.ReadOnly = true;
            this.txtKSChon = new TextBox();
            this.txtKSChon.Name = "txtKSChon";
            this.txtKSChon.Size = new Size(205, 29);
            this.txtKSChon.ReadOnly = true;
            this.dtPH = new DateTimePicker();
            this.dtPH.Name = "dtPH";
            this.dtPH.Format = DateTimePickerFormat.Short;
            this.dtPH.Size = new Size(205, 30);
            this.numDiem = new NumericUpDown();
            this.numDiem.Name = "numDiem";
            this.numDiem.Maximum = 5;
            this.numDiem.Minimum = 1;
            this.numDiem.Value = 1;
            this.numDiem.Size = new Size(205, 28);
            this.txtGopY = new TextBox();
            this.txtGopY.Name = "txtGopY";
            this.txtGopY.Size = new Size(205, 29);
            this.btnGhiPH = new Button();
            this.btnGhiPH.Name = "btnGhiPH";
            this.btnGhiPH.Text = "Ghi nhận góp ý";
            this.btnGhiPH.Size = new Size(190, 36);
            this.btnGhiPH.FlatStyle = FlatStyle.Standard;
            this.btnDong = new Button();
            this.btnDong.Name = "btnDong";
            this.btnDong.Text = "Đóng";
            this.btnDong.Size = new Size(190, 36);
            this.btnDong.FlatStyle = FlatStyle.Standard;
            this.dgvDoan.SelectionChanged += new EventHandler(this.dgvDoan_SelectionChanged);
            this.btnThanhToan.Click += new EventHandler(this.btnThanhToan_Click);
            this.cboLoaiKS.SelectedIndexChanged += new EventHandler(this.cboLoaiKS_SelectedIndexChanged);
            this.btnGui.Click += new EventHandler(this.btnGui_Click);
            this.dgvKS.SelectionChanged += new EventHandler(this.dgvKS_SelectionChanged);
            this.btnGhiPH.Click += new EventHandler(this.btnGhiPH_Click);
            this.btnDong.Click += new EventHandler(this.btnDong_Click);
            this.cboLoaiKS.Items.AddRange(new object[] { "LE", "DOAN" });
            this.AutoScaleMode = AutoScaleMode.Font;
            this.ClientSize = new Size(1120, 760);
            this.MinimumSize = new Size(800, 600);
            this.StartPosition = FormStartPosition.CenterScreen;
            this.Font = new Font("Segoe UI", 9.5f);
            this.Text = "Kết thúc tour - khảo sát";
            this.Load += new EventHandler(this.FrmKetThucKhaoSat_Load);
            this.mainLayout = new TableLayoutPanel();
            this.mainLayout.Name = "mainLayout";
            this.mainLayout.Dock = DockStyle.Fill;
            this.mainLayout.Padding = new Padding(12);
            this.mainLayout.ColumnCount = 1;
            this.mainLayout.RowCount = 3;
            this.mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 70F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 55F));
            this.Controls.Add(this.mainLayout);
            this.lblTieuDe = new Label();
            this.lblTieuDe.Name = "lblTieuDe";
            this.lblTieuDe.Text = "Kết thúc tour - khảo sát";
            this.lblTieuDe.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
            this.lblTieuDe.ForeColor = Color.FromArgb(33, 65, 94);
            this.lblTieuDe.Dock = DockStyle.Fill;
            this.lblTieuDe.TextAlign = ContentAlignment.MiddleCenter;
            this.mainLayout.Controls.Add(this.lblTieuDe, 0, 0);
            this.tabKT.Dock = DockStyle.Fill;
            this.tabPage0 = new TabPage();
            this.tabPage0.Name = "tabPage0";
            this.tabPage0.Text = "Thanh toán sau tour (đoàn)";
            this.tabPage0.Padding = new Padding(8);
            this.tabLayout0 = new TableLayoutPanel();
            this.tabLayout0.Name = "tabLayout0";
            this.tabLayout0.Dock = DockStyle.Fill;
            this.tabLayout0.ColumnCount = 1;
            this.tabLayout0.RowCount = 2;
            this.tabLayout0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.tabLayout0.RowStyles.Add(new RowStyle(SizeType.Percent, 64F));
            this.tabLayout0.RowStyles.Add(new RowStyle(SizeType.Percent, 36F));
            this.fieldsTab0 = new FlowLayoutPanel();
            this.fieldsTab0.Name = "fieldsTab0";
            this.fieldsTab0.Dock = DockStyle.Fill;
            this.fieldsTab0.AutoScroll = true;
            this.fieldsTab0.WrapContents = true;
            this.fieldsTab0.Padding = new Padding(6);
            this.fieldsTab0.FlowDirection = FlowDirection.LeftToRight;
            this.panTab0Field0 = new Panel();
            this.panTab0Field0.Name = "panTab0Field0";
            this.panTab0Field0.Size = new Size(230, 67);
            this.panTab0Field0.Margin = new Padding(5, 5, 5, 2);
            this.lblTab0Field0 = new Label();
            this.lblTab0Field0.Name = "lblTab0Field0";
            this.lblTab0Field0.Text = "Số thanh toán";
            this.lblTab0Field0.AutoSize = false;
            this.lblTab0Field0.Size = new Size(215, 20);
            this.lblTab0Field0.Location = new Point(6, 2);
            this.panTab0Field0.Controls.Add(this.lblTab0Field0);
            this.txtSoTT.Location = new Point(6, 27);
            this.txtSoTT.Size = new Size(210, 28);
            this.panTab0Field0.Controls.Add(this.txtSoTT);
            this.fieldsTab0.Controls.Add(this.panTab0Field0);
            this.panTab0Field1 = new Panel();
            this.panTab0Field1.Name = "panTab0Field1";
            this.panTab0Field1.Size = new Size(230, 67);
            this.panTab0Field1.Margin = new Padding(5, 5, 5, 2);
            this.lblTab0Field1 = new Label();
            this.lblTab0Field1.Name = "lblTab0Field1";
            this.lblTab0Field1.Text = "Phiếu đoàn";
            this.lblTab0Field1.AutoSize = false;
            this.lblTab0Field1.Size = new Size(215, 20);
            this.lblTab0Field1.Location = new Point(6, 2);
            this.panTab0Field1.Controls.Add(this.lblTab0Field1);
            this.txtSoDK.Location = new Point(6, 27);
            this.txtSoDK.Size = new Size(210, 28);
            this.panTab0Field1.Controls.Add(this.txtSoDK);
            this.fieldsTab0.Controls.Add(this.panTab0Field1);
            this.panTab0Field2 = new Panel();
            this.panTab0Field2.Name = "panTab0Field2";
            this.panTab0Field2.Size = new Size(230, 67);
            this.panTab0Field2.Margin = new Padding(5, 5, 5, 2);
            this.lblTab0Field2 = new Label();
            this.lblTab0Field2.Name = "lblTab0Field2";
            this.lblTab0Field2.Text = "Ngày thanh toán";
            this.lblTab0Field2.AutoSize = false;
            this.lblTab0Field2.Size = new Size(215, 20);
            this.lblTab0Field2.Location = new Point(6, 2);
            this.panTab0Field2.Controls.Add(this.lblTab0Field2);
            this.dtTT.Location = new Point(6, 27);
            this.dtTT.Size = new Size(210, 28);
            this.panTab0Field2.Controls.Add(this.dtTT);
            this.fieldsTab0.Controls.Add(this.panTab0Field2);
            this.panTab0Field3 = new Panel();
            this.panTab0Field3.Name = "panTab0Field3";
            this.panTab0Field3.Size = new Size(230, 67);
            this.panTab0Field3.Margin = new Padding(5, 5, 5, 2);
            this.lblTab0Field3 = new Label();
            this.lblTab0Field3.Name = "lblTab0Field3";
            this.lblTab0Field3.Text = "Số tiền";
            this.lblTab0Field3.AutoSize = false;
            this.lblTab0Field3.Size = new Size(215, 20);
            this.lblTab0Field3.Location = new Point(6, 2);
            this.panTab0Field3.Controls.Add(this.lblTab0Field3);
            this.numTien.Location = new Point(6, 27);
            this.numTien.Size = new Size(210, 28);
            this.panTab0Field3.Controls.Add(this.numTien);
            this.fieldsTab0.Controls.Add(this.panTab0Field3);
            this.panTab0Field4 = new Panel();
            this.panTab0Field4.Name = "panTab0Field4";
            this.panTab0Field4.Size = new Size(230, 67);
            this.panTab0Field4.Margin = new Padding(5, 5, 5, 2);
            this.lblTab0Field4 = new Label();
            this.lblTab0Field4.Name = "lblTab0Field4";
            this.lblTab0Field4.Text = "Ghi chú";
            this.lblTab0Field4.AutoSize = false;
            this.lblTab0Field4.Size = new Size(215, 20);
            this.lblTab0Field4.Location = new Point(6, 2);
            this.panTab0Field4.Controls.Add(this.lblTab0Field4);
            this.txtGhiChu.Location = new Point(6, 27);
            this.txtGhiChu.Size = new Size(210, 28);
            this.panTab0Field4.Controls.Add(this.txtGhiChu);
            this.fieldsTab0.Controls.Add(this.panTab0Field4);
            this.panTab0Field5 = new Panel();
            this.panTab0Field5.Name = "panTab0Field5";
            this.panTab0Field5.Size = new Size(230, 67);
            this.panTab0Field5.Margin = new Padding(5, 5, 5, 2);
            this.lblTab0Field5 = new Label();
            this.lblTab0Field5.Name = "lblTab0Field5";
            this.lblTab0Field5.Text = "Ghi nhận thanh toán";
            this.lblTab0Field5.AutoSize = false;
            this.lblTab0Field5.Size = new Size(215, 20);
            this.lblTab0Field5.Location = new Point(6, 2);
            this.panTab0Field5.Controls.Add(this.lblTab0Field5);
            this.btnThanhToan.Location = new Point(6, 27);
            this.btnThanhToan.Size = new Size(210, 34);
            this.panTab0Field5.Controls.Add(this.btnThanhToan);
            this.fieldsTab0.Controls.Add(this.panTab0Field5);
            this.tabLayout0.Controls.Add(this.dgvDoan, 0, 0);
            this.tabLayout0.Controls.Add(this.fieldsTab0, 0, 1);
            this.tabPage0.Controls.Add(this.tabLayout0);
            this.tabKT.Controls.Add(this.tabPage0);
            this.tabPage1 = new TabPage();
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Text = "Khảo sát khách hàng";
            this.tabPage1.Padding = new Padding(8);
            this.tabLayout1 = new TableLayoutPanel();
            this.tabLayout1.Name = "tabLayout1";
            this.tabLayout1.Dock = DockStyle.Fill;
            this.tabLayout1.ColumnCount = 1;
            this.tabLayout1.RowCount = 2;
            this.tabLayout1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.tabLayout1.RowStyles.Add(new RowStyle(SizeType.Percent, 64F));
            this.tabLayout1.RowStyles.Add(new RowStyle(SizeType.Percent, 36F));
            this.fieldsTab1 = new FlowLayoutPanel();
            this.fieldsTab1.Name = "fieldsTab1";
            this.fieldsTab1.Dock = DockStyle.Fill;
            this.fieldsTab1.AutoScroll = true;
            this.fieldsTab1.WrapContents = true;
            this.fieldsTab1.Padding = new Padding(6);
            this.fieldsTab1.FlowDirection = FlowDirection.LeftToRight;
            this.panTab1Field0 = new Panel();
            this.panTab1Field0.Name = "panTab1Field0";
            this.panTab1Field0.Size = new Size(230, 67);
            this.panTab1Field0.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field0 = new Label();
            this.lblTab1Field0.Name = "lblTab1Field0";
            this.lblTab1Field0.Text = "Loại khách";
            this.lblTab1Field0.AutoSize = false;
            this.lblTab1Field0.Size = new Size(215, 20);
            this.lblTab1Field0.Location = new Point(6, 2);
            this.panTab1Field0.Controls.Add(this.lblTab1Field0);
            this.cboLoaiKS.Location = new Point(6, 27);
            this.cboLoaiKS.Size = new Size(210, 28);
            this.panTab1Field0.Controls.Add(this.cboLoaiKS);
            this.fieldsTab1.Controls.Add(this.panTab1Field0);
            this.panTab1Field1 = new Panel();
            this.panTab1Field1.Name = "panTab1Field1";
            this.panTab1Field1.Size = new Size(230, 67);
            this.panTab1Field1.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field1 = new Label();
            this.lblTab1Field1.Name = "lblTab1Field1";
            this.lblTab1Field1.Text = "Đăng ký đã kết thúc";
            this.lblTab1Field1.AutoSize = false;
            this.lblTab1Field1.Size = new Size(215, 20);
            this.lblTab1Field1.Location = new Point(6, 2);
            this.panTab1Field1.Controls.Add(this.lblTab1Field1);
            this.cboDangKy.Location = new Point(6, 27);
            this.cboDangKy.Size = new Size(210, 28);
            this.panTab1Field1.Controls.Add(this.cboDangKy);
            this.fieldsTab1.Controls.Add(this.panTab1Field1);
            this.panTab1Field2 = new Panel();
            this.panTab1Field2.Name = "panTab1Field2";
            this.panTab1Field2.Size = new Size(230, 67);
            this.panTab1Field2.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field2 = new Label();
            this.lblTab1Field2.Name = "lblTab1Field2";
            this.lblTab1Field2.Text = "Mã KS";
            this.lblTab1Field2.AutoSize = false;
            this.lblTab1Field2.Size = new Size(215, 20);
            this.lblTab1Field2.Location = new Point(6, 2);
            this.panTab1Field2.Controls.Add(this.lblTab1Field2);
            this.txtMaKS.Location = new Point(6, 27);
            this.txtMaKS.Size = new Size(210, 28);
            this.panTab1Field2.Controls.Add(this.txtMaKS);
            this.fieldsTab1.Controls.Add(this.panTab1Field2);
            this.panTab1Field3 = new Panel();
            this.panTab1Field3.Name = "panTab1Field3";
            this.panTab1Field3.Size = new Size(230, 67);
            this.panTab1Field3.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field3 = new Label();
            this.lblTab1Field3.Name = "lblTab1Field3";
            this.lblTab1Field3.Text = "Ngày gửi";
            this.lblTab1Field3.AutoSize = false;
            this.lblTab1Field3.Size = new Size(215, 20);
            this.lblTab1Field3.Location = new Point(6, 2);
            this.panTab1Field3.Controls.Add(this.lblTab1Field3);
            this.dtGui.Location = new Point(6, 27);
            this.dtGui.Size = new Size(210, 28);
            this.panTab1Field3.Controls.Add(this.dtGui);
            this.fieldsTab1.Controls.Add(this.panTab1Field3);
            this.panTab1Field4 = new Panel();
            this.panTab1Field4.Name = "panTab1Field4";
            this.panTab1Field4.Size = new Size(230, 67);
            this.panTab1Field4.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field4 = new Label();
            this.lblTab1Field4.Name = "lblTab1Field4";
            this.lblTab1Field4.Text = "Gửi phiếu khảo sát";
            this.lblTab1Field4.AutoSize = false;
            this.lblTab1Field4.Size = new Size(215, 20);
            this.lblTab1Field4.Location = new Point(6, 2);
            this.panTab1Field4.Controls.Add(this.lblTab1Field4);
            this.btnGui.Location = new Point(6, 27);
            this.btnGui.Size = new Size(210, 34);
            this.panTab1Field4.Controls.Add(this.btnGui);
            this.fieldsTab1.Controls.Add(this.panTab1Field4);
            this.panTab1Field5 = new Panel();
            this.panTab1Field5.Name = "panTab1Field5";
            this.panTab1Field5.Size = new Size(230, 67);
            this.panTab1Field5.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field5 = new Label();
            this.lblTab1Field5.Name = "lblTab1Field5";
            this.lblTab1Field5.Text = "Phiếu chọn";
            this.lblTab1Field5.AutoSize = false;
            this.lblTab1Field5.Size = new Size(215, 20);
            this.lblTab1Field5.Location = new Point(6, 2);
            this.panTab1Field5.Controls.Add(this.lblTab1Field5);
            this.txtKSChon.Location = new Point(6, 27);
            this.txtKSChon.Size = new Size(210, 28);
            this.panTab1Field5.Controls.Add(this.txtKSChon);
            this.fieldsTab1.Controls.Add(this.panTab1Field5);
            this.panTab1Field6 = new Panel();
            this.panTab1Field6.Name = "panTab1Field6";
            this.panTab1Field6.Size = new Size(230, 67);
            this.panTab1Field6.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field6 = new Label();
            this.lblTab1Field6.Name = "lblTab1Field6";
            this.lblTab1Field6.Text = "Ngày phản hồi";
            this.lblTab1Field6.AutoSize = false;
            this.lblTab1Field6.Size = new Size(215, 20);
            this.lblTab1Field6.Location = new Point(6, 2);
            this.panTab1Field6.Controls.Add(this.lblTab1Field6);
            this.dtPH.Location = new Point(6, 27);
            this.dtPH.Size = new Size(210, 28);
            this.panTab1Field6.Controls.Add(this.dtPH);
            this.fieldsTab1.Controls.Add(this.panTab1Field6);
            this.panTab1Field7 = new Panel();
            this.panTab1Field7.Name = "panTab1Field7";
            this.panTab1Field7.Size = new Size(230, 67);
            this.panTab1Field7.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field7 = new Label();
            this.lblTab1Field7.Name = "lblTab1Field7";
            this.lblTab1Field7.Text = "Điểm (1-5)";
            this.lblTab1Field7.AutoSize = false;
            this.lblTab1Field7.Size = new Size(215, 20);
            this.lblTab1Field7.Location = new Point(6, 2);
            this.panTab1Field7.Controls.Add(this.lblTab1Field7);
            this.numDiem.Location = new Point(6, 27);
            this.numDiem.Size = new Size(210, 28);
            this.panTab1Field7.Controls.Add(this.numDiem);
            this.fieldsTab1.Controls.Add(this.panTab1Field7);
            this.panTab1Field8 = new Panel();
            this.panTab1Field8.Name = "panTab1Field8";
            this.panTab1Field8.Size = new Size(230, 67);
            this.panTab1Field8.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field8 = new Label();
            this.lblTab1Field8.Name = "lblTab1Field8";
            this.lblTab1Field8.Text = "Góp ý";
            this.lblTab1Field8.AutoSize = false;
            this.lblTab1Field8.Size = new Size(215, 20);
            this.lblTab1Field8.Location = new Point(6, 2);
            this.panTab1Field8.Controls.Add(this.lblTab1Field8);
            this.txtGopY.Location = new Point(6, 27);
            this.txtGopY.Size = new Size(210, 28);
            this.panTab1Field8.Controls.Add(this.txtGopY);
            this.fieldsTab1.Controls.Add(this.panTab1Field8);
            this.panTab1Field9 = new Panel();
            this.panTab1Field9.Name = "panTab1Field9";
            this.panTab1Field9.Size = new Size(230, 67);
            this.panTab1Field9.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field9 = new Label();
            this.lblTab1Field9.Name = "lblTab1Field9";
            this.lblTab1Field9.Text = "Ghi nhận góp ý";
            this.lblTab1Field9.AutoSize = false;
            this.lblTab1Field9.Size = new Size(215, 20);
            this.lblTab1Field9.Location = new Point(6, 2);
            this.panTab1Field9.Controls.Add(this.lblTab1Field9);
            this.btnGhiPH.Location = new Point(6, 27);
            this.btnGhiPH.Size = new Size(210, 34);
            this.panTab1Field9.Controls.Add(this.btnGhiPH);
            this.fieldsTab1.Controls.Add(this.panTab1Field9);
            this.tabLayout1.Controls.Add(this.dgvKS, 0, 0);
            this.tabLayout1.Controls.Add(this.fieldsTab1, 0, 1);
            this.tabPage1.Controls.Add(this.tabLayout1);
            this.tabKT.Controls.Add(this.tabPage1);
            this.mainLayout.Controls.Add(this.tabKT, 0, 1);
            this.footerLayout = new FlowLayoutPanel();
            this.footerLayout.Name = "footerLayout";
            this.footerLayout.Dock = DockStyle.Fill;
            this.footerLayout.FlowDirection = FlowDirection.RightToLeft;
            this.footerLayout.Padding = new Padding(6);
            this.btnDong.Size = new Size(120, 35);
            this.footerLayout.Controls.Add(this.btnDong);
            this.mainLayout.Controls.Add(this.footerLayout, 0, 2);
            this.ResumeLayout(false);
        }
    }
}
