// Giao diện WinForms tạo bằng các control và container chuẩn để Visual Studio Designer hiển thị.
// Có thể chỉnh trực tiếp vị trí, kích thước, Text trong tab Design.
using System;
using System.Drawing;
using System.Windows.Forms;

namespace QuanLyCongTyDuLich.Forms
{
    public partial class FrmLuongThongKe
    {
        private System.ComponentModel.IContainer components = null;
        private TabControl tabTK;
        private NumericUpDown numThang;
        private NumericUpDown numNam;
        private Button btnLuong;
        private DataGridView dgvLuong;
        private DateTimePicker dtTu;
        private DateTimePicker dtDen;
        private Button btnTongHop;
        private DataGridView dgvTongHop;
        private Button btnDong;
        private TableLayoutPanel mainLayout;
        private Label lblTieuDe;
        private TabPage tabPage0;
        private TableLayoutPanel tabLayout0;
        private FlowLayoutPanel fieldsTab0;
        private Panel panTab0Field0;
        private Label lblTab0Field0;
        private Panel panTab0Field1;
        private Label lblTab0Field1;
        private Panel panTab0Field2;
        private Label lblTab0Field2;
        private TabPage tabPage1;
        private TableLayoutPanel tabLayout1;
        private FlowLayoutPanel fieldsTab1;
        private Panel panTab1Field0;
        private Label lblTab1Field0;
        private Panel panTab1Field1;
        private Label lblTab1Field1;
        private Panel panTab1Field2;
        private Label lblTab1Field2;
        private FlowLayoutPanel footerLayout;

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null) this.components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.tabTK = new TabControl();
            this.tabTK.Name = "tabTK";
            this.numThang = new NumericUpDown();
            this.numThang.Name = "numThang";
            this.numThang.Maximum = 12;
            this.numThang.Minimum = 1;
            this.numThang.Value = 1;
            this.numThang.Size = new Size(205, 28);
            this.numNam = new NumericUpDown();
            this.numNam.Name = "numNam";
            this.numNam.Maximum = 2100;
            this.numNam.Minimum = 2020;
            this.numNam.Size = new Size(205, 28);
            this.btnLuong = new Button();
            this.btnLuong.Name = "btnLuong";
            this.btnLuong.Text = "Tính lương";
            this.btnLuong.Size = new Size(190, 36);
            this.btnLuong.FlatStyle = FlatStyle.Standard;
            this.dgvLuong = new DataGridView();
            this.dgvLuong.Name = "dgvLuong";
            this.dgvLuong.Dock = DockStyle.Fill;
            this.dgvLuong.BackgroundColor = Color.White;
            this.dgvLuong.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
            this.dgvLuong.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvLuong.MultiSelect = false;
            this.dgvLuong.RowHeadersVisible = false;
            this.dgvLuong.AllowUserToAddRows = false;
            this.dgvLuong.AllowUserToDeleteRows = false;
            this.dgvLuong.ReadOnly = true;
            this.dtTu = new DateTimePicker();
            this.dtTu.Name = "dtTu";
            this.dtTu.Format = DateTimePickerFormat.Short;
            this.dtTu.Size = new Size(205, 30);
            this.dtDen = new DateTimePicker();
            this.dtDen.Name = "dtDen";
            this.dtDen.Format = DateTimePickerFormat.Short;
            this.dtDen.Size = new Size(205, 30);
            this.btnTongHop = new Button();
            this.btnTongHop.Name = "btnTongHop";
            this.btnTongHop.Text = "Thống kê";
            this.btnTongHop.Size = new Size(190, 36);
            this.btnTongHop.FlatStyle = FlatStyle.Standard;
            this.dgvTongHop = new DataGridView();
            this.dgvTongHop.Name = "dgvTongHop";
            this.dgvTongHop.Dock = DockStyle.Fill;
            this.dgvTongHop.BackgroundColor = Color.White;
            this.dgvTongHop.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
            this.dgvTongHop.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvTongHop.MultiSelect = false;
            this.dgvTongHop.RowHeadersVisible = false;
            this.dgvTongHop.AllowUserToAddRows = false;
            this.dgvTongHop.AllowUserToDeleteRows = false;
            this.dgvTongHop.ReadOnly = true;
            this.btnDong = new Button();
            this.btnDong.Name = "btnDong";
            this.btnDong.Text = "Đóng";
            this.btnDong.Size = new Size(190, 36);
            this.btnDong.FlatStyle = FlatStyle.Standard;
            this.btnLuong.Click += new EventHandler(this.btnLuong_Click);
            this.btnTongHop.Click += new EventHandler(this.btnTongHop_Click);
            this.btnDong.Click += new EventHandler(this.btnDong_Click);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.ClientSize = new Size(1120, 760);
            this.MinimumSize = new Size(800, 600);
            this.StartPosition = FormStartPosition.CenterScreen;
            this.Font = new Font("Segoe UI", 9.5f);
            this.Text = "Lương và thống kê";
            this.Load += new EventHandler(this.FrmLuongThongKe_Load);
            this.mainLayout = new TableLayoutPanel();
            this.mainLayout.Name = "mainLayout";
            this.mainLayout.Dock = DockStyle.Fill;
            this.mainLayout.Padding = new Padding(12);
            this.mainLayout.ColumnCount = 1;
            this.mainLayout.RowCount = 3;
            this.mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 70F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 55F));
            this.Controls.Add(this.mainLayout);
            this.lblTieuDe = new Label();
            this.lblTieuDe.Name = "lblTieuDe";
            this.lblTieuDe.Text = "Lương và thống kê";
            this.lblTieuDe.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
            this.lblTieuDe.ForeColor = Color.FromArgb(33, 65, 94);
            this.lblTieuDe.Dock = DockStyle.Fill;
            this.lblTieuDe.TextAlign = ContentAlignment.MiddleCenter;
            this.mainLayout.Controls.Add(this.lblTieuDe, 0, 0);
            this.tabTK.Dock = DockStyle.Fill;
            this.tabPage0 = new TabPage();
            this.tabPage0.Name = "tabPage0";
            this.tabPage0.Text = "Lương hướng dẫn viên";
            this.tabPage0.Padding = new Padding(8);
            this.tabLayout0 = new TableLayoutPanel();
            this.tabLayout0.Name = "tabLayout0";
            this.tabLayout0.Dock = DockStyle.Fill;
            this.tabLayout0.ColumnCount = 1;
            this.tabLayout0.RowCount = 2;
            this.tabLayout0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.tabLayout0.RowStyles.Add(new RowStyle(SizeType.Percent, 64F));
            this.tabLayout0.RowStyles.Add(new RowStyle(SizeType.Percent, 36F));
            this.fieldsTab0 = new FlowLayoutPanel();
            this.fieldsTab0.Name = "fieldsTab0";
            this.fieldsTab0.Dock = DockStyle.Fill;
            this.fieldsTab0.AutoScroll = true;
            this.fieldsTab0.WrapContents = true;
            this.fieldsTab0.Padding = new Padding(6);
            this.fieldsTab0.FlowDirection = FlowDirection.LeftToRight;
            this.panTab0Field0 = new Panel();
            this.panTab0Field0.Name = "panTab0Field0";
            this.panTab0Field0.Size = new Size(230, 67);
            this.panTab0Field0.Margin = new Padding(5, 5, 5, 2);
            this.lblTab0Field0 = new Label();
            this.lblTab0Field0.Name = "lblTab0Field0";
            this.lblTab0Field0.Text = "Tháng";
            this.lblTab0Field0.AutoSize = false;
            this.lblTab0Field0.Size = new Size(215, 20);
            this.lblTab0Field0.Location = new Point(6, 2);
            this.panTab0Field0.Controls.Add(this.lblTab0Field0);
            this.numThang.Location = new Point(6, 27);
            this.numThang.Size = new Size(210, 28);
            this.panTab0Field0.Controls.Add(this.numThang);
            this.fieldsTab0.Controls.Add(this.panTab0Field0);
            this.panTab0Field1 = new Panel();
            this.panTab0Field1.Name = "panTab0Field1";
            this.panTab0Field1.Size = new Size(230, 67);
            this.panTab0Field1.Margin = new Padding(5, 5, 5, 2);
            this.lblTab0Field1 = new Label();
            this.lblTab0Field1.Name = "lblTab0Field1";
            this.lblTab0Field1.Text = "Năm";
            this.lblTab0Field1.AutoSize = false;
            this.lblTab0Field1.Size = new Size(215, 20);
            this.lblTab0Field1.Location = new Point(6, 2);
            this.panTab0Field1.Controls.Add(this.lblTab0Field1);
            this.numNam.Location = new Point(6, 27);
            this.numNam.Size = new Size(210, 28);
            this.panTab0Field1.Controls.Add(this.numNam);
            this.fieldsTab0.Controls.Add(this.panTab0Field1);
            this.panTab0Field2 = new Panel();
            this.panTab0Field2.Name = "panTab0Field2";
            this.panTab0Field2.Size = new Size(230, 67);
            this.panTab0Field2.Margin = new Padding(5, 5, 5, 2);
            this.lblTab0Field2 = new Label();
            this.lblTab0Field2.Name = "lblTab0Field2";
            this.lblTab0Field2.Text = "Tính lương";
            this.lblTab0Field2.AutoSize = false;
            this.lblTab0Field2.Size = new Size(215, 20);
            this.lblTab0Field2.Location = new Point(6, 2);
            this.panTab0Field2.Controls.Add(this.lblTab0Field2);
            this.btnLuong.Location = new Point(6, 27);
            this.btnLuong.Size = new Size(210, 34);
            this.panTab0Field2.Controls.Add(this.btnLuong);
            this.fieldsTab0.Controls.Add(this.panTab0Field2);
            this.tabLayout0.Controls.Add(this.dgvLuong, 0, 0);
            this.tabLayout0.Controls.Add(this.fieldsTab0, 0, 1);
            this.tabPage0.Controls.Add(this.tabLayout0);
            this.tabTK.Controls.Add(this.tabPage0);
            this.tabPage1 = new TabPage();
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Text = "Thống kê tổng hợp";
            this.tabPage1.Padding = new Padding(8);
            this.tabLayout1 = new TableLayoutPanel();
            this.tabLayout1.Name = "tabLayout1";
            this.tabLayout1.Dock = DockStyle.Fill;
            this.tabLayout1.ColumnCount = 1;
            this.tabLayout1.RowCount = 2;
            this.tabLayout1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.tabLayout1.RowStyles.Add(new RowStyle(SizeType.Percent, 64F));
            this.tabLayout1.RowStyles.Add(new RowStyle(SizeType.Percent, 36F));
            this.fieldsTab1 = new FlowLayoutPanel();
            this.fieldsTab1.Name = "fieldsTab1";
            this.fieldsTab1.Dock = DockStyle.Fill;
            this.fieldsTab1.AutoScroll = true;
            this.fieldsTab1.WrapContents = true;
            this.fieldsTab1.Padding = new Padding(6);
            this.fieldsTab1.FlowDirection = FlowDirection.LeftToRight;
            this.panTab1Field0 = new Panel();
            this.panTab1Field0.Name = "panTab1Field0";
            this.panTab1Field0.Size = new Size(230, 67);
            this.panTab1Field0.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field0 = new Label();
            this.lblTab1Field0.Name = "lblTab1Field0";
            this.lblTab1Field0.Text = "Từ ngày";
            this.lblTab1Field0.AutoSize = false;
            this.lblTab1Field0.Size = new Size(215, 20);
            this.lblTab1Field0.Location = new Point(6, 2);
            this.panTab1Field0.Controls.Add(this.lblTab1Field0);
            this.dtTu.Location = new Point(6, 27);
            this.dtTu.Size = new Size(210, 28);
            this.panTab1Field0.Controls.Add(this.dtTu);
            this.fieldsTab1.Controls.Add(this.panTab1Field0);
            this.panTab1Field1 = new Panel();
            this.panTab1Field1.Name = "panTab1Field1";
            this.panTab1Field1.Size = new Size(230, 67);
            this.panTab1Field1.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field1 = new Label();
            this.lblTab1Field1.Name = "lblTab1Field1";
            this.lblTab1Field1.Text = "Đến ngày";
            this.lblTab1Field1.AutoSize = false;
            this.lblTab1Field1.Size = new Size(215, 20);
            this.lblTab1Field1.Location = new Point(6, 2);
            this.panTab1Field1.Controls.Add(this.lblTab1Field1);
            this.dtDen.Location = new Point(6, 27);
            this.dtDen.Size = new Size(210, 28);
            this.panTab1Field1.Controls.Add(this.dtDen);
            this.fieldsTab1.Controls.Add(this.panTab1Field1);
            this.panTab1Field2 = new Panel();
            this.panTab1Field2.Name = "panTab1Field2";
            this.panTab1Field2.Size = new Size(230, 67);
            this.panTab1Field2.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field2 = new Label();
            this.lblTab1Field2.Name = "lblTab1Field2";
            this.lblTab1Field2.Text = "Thống kê";
            this.lblTab1Field2.AutoSize = false;
            this.lblTab1Field2.Size = new Size(215, 20);
            this.lblTab1Field2.Location = new Point(6, 2);
            this.panTab1Field2.Controls.Add(this.lblTab1Field2);
            this.btnTongHop.Location = new Point(6, 27);
            this.btnTongHop.Size = new Size(210, 34);
            this.panTab1Field2.Controls.Add(this.btnTongHop);
            this.fieldsTab1.Controls.Add(this.panTab1Field2);
            this.tabLayout1.Controls.Add(this.dgvTongHop, 0, 0);
            this.tabLayout1.Controls.Add(this.fieldsTab1, 0, 1);
            this.tabPage1.Controls.Add(this.tabLayout1);
            this.tabTK.Controls.Add(this.tabPage1);
            this.mainLayout.Controls.Add(this.tabTK, 0, 1);
            this.footerLayout = new FlowLayoutPanel();
            this.footerLayout.Name = "footerLayout";
            this.footerLayout.Dock = DockStyle.Fill;
            this.footerLayout.FlowDirection = FlowDirection.RightToLeft;
            this.footerLayout.Padding = new Padding(6);
            this.btnDong.Size = new Size(120, 35);
            this.footerLayout.Controls.Add(this.btnDong);
            this.mainLayout.Controls.Add(this.footerLayout, 0, 2);
            this.ResumeLayout(false);
        }
    }
}
