// Giao diện WinForms tạo bằng các control và container chuẩn để Visual Studio Designer hiển thị.
// Có thể chỉnh trực tiếp vị trí, kích thước, Text trong tab Design.
using System;
using System.Drawing;
using System.Windows.Forms;

namespace QuanLyCongTyDuLich.Forms
{
    public partial class FrmPhanCongHDV
    {
        private System.ComponentModel.IContainer components = null;
        private TextBox txtMaPC;
        private ComboBox cboHDV;
        private ComboBox cboLoai;
        private ComboBox cboDoiTuong;
        private NumericUpDown numThuLao;
        private Button btnPhanCong;
        private DataGridView dgv;
        private Button btnDong;
        private TableLayoutPanel mainLayout;
        private Label lblTieuDe;
        private FlowLayoutPanel flowFields;
        private Panel panField0;
        private Label lblField0;
        private Panel panField1;
        private Label lblField1;
        private Panel panField2;
        private Label lblField2;
        private Panel panField3;
        private Label lblField3;
        private Panel panField4;
        private Label lblField4;
        private Panel panField5;
        private Label lblField5;
        private FlowLayoutPanel footerLayout;

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null) this.components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.txtMaPC = new TextBox();
            this.txtMaPC.Name = "txtMaPC";
            this.txtMaPC.Size = new Size(205, 29);
            this.cboHDV = new ComboBox();
            this.cboHDV.Name = "cboHDV";
            this.cboHDV.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboLoai = new ComboBox();
            this.cboLoai.Name = "cboLoai";
            this.cboLoai.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboDoiTuong = new ComboBox();
            this.cboDoiTuong.Name = "cboDoiTuong";
            this.cboDoiTuong.DropDownStyle = ComboBoxStyle.DropDownList;
            this.numThuLao = new NumericUpDown();
            this.numThuLao.Name = "numThuLao";
            this.numThuLao.Maximum = 100000000000M;
            this.numThuLao.Minimum = 0;
            this.numThuLao.Size = new Size(205, 28);
            this.btnPhanCong = new Button();
            this.btnPhanCong.Name = "btnPhanCong";
            this.btnPhanCong.Text = "Phân công";
            this.btnPhanCong.Size = new Size(190, 36);
            this.btnPhanCong.FlatStyle = FlatStyle.Standard;
            this.dgv = new DataGridView();
            this.dgv.Name = "dgv";
            this.dgv.Dock = DockStyle.Fill;
            this.dgv.BackgroundColor = Color.White;
            this.dgv.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
            this.dgv.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgv.MultiSelect = false;
            this.dgv.RowHeadersVisible = false;
            this.dgv.AllowUserToAddRows = false;
            this.dgv.AllowUserToDeleteRows = false;
            this.dgv.ReadOnly = true;
            this.btnDong = new Button();
            this.btnDong.Name = "btnDong";
            this.btnDong.Text = "Đóng";
            this.btnDong.Size = new Size(190, 36);
            this.btnDong.FlatStyle = FlatStyle.Standard;
            this.cboLoai.SelectedIndexChanged += new EventHandler(this.cboLoai_SelectedIndexChanged);
            this.btnPhanCong.Click += new EventHandler(this.btnPhanCong_Click);
            this.btnDong.Click += new EventHandler(this.btnDong_Click);
            this.cboLoai.Items.AddRange(new object[] { "LE", "DOAN" });
            this.AutoScaleMode = AutoScaleMode.Font;
            this.ClientSize = new Size(1120, 760);
            this.MinimumSize = new Size(800, 600);
            this.StartPosition = FormStartPosition.CenterScreen;
            this.Font = new Font("Segoe UI", 9.5f);
            this.Text = "Phân công hướng dẫn viên";
            this.Load += new EventHandler(this.FrmPhanCongHDV_Load);
            this.mainLayout = new TableLayoutPanel();
            this.mainLayout.Name = "mainLayout";
            this.mainLayout.Dock = DockStyle.Fill;
            this.mainLayout.Padding = new Padding(12);
            this.mainLayout.ColumnCount = 1;
            this.mainLayout.RowCount = 4;
            this.mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 55F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 180F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 55F));
            this.Controls.Add(this.mainLayout);
            this.lblTieuDe = new Label();
            this.lblTieuDe.Name = "lblTieuDe";
            this.lblTieuDe.Text = "Phân công hướng dẫn viên";
            this.lblTieuDe.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
            this.lblTieuDe.ForeColor = Color.FromArgb(33, 65, 94);
            this.lblTieuDe.Dock = DockStyle.Fill;
            this.lblTieuDe.TextAlign = ContentAlignment.MiddleCenter;
            this.mainLayout.Controls.Add(this.lblTieuDe, 0, 0);
            this.flowFields = new FlowLayoutPanel();
            this.flowFields.Name = "flowFields";
            this.flowFields.Dock = DockStyle.Fill;
            this.flowFields.AutoScroll = true;
            this.flowFields.WrapContents = true;
            this.flowFields.Padding = new Padding(6);
            this.flowFields.FlowDirection = FlowDirection.LeftToRight;
            this.panField0 = new Panel();
            this.panField0.Name = "panField0";
            this.panField0.Size = new Size(230, 67);
            this.panField0.Margin = new Padding(5, 5, 5, 2);
            this.lblField0 = new Label();
            this.lblField0.Name = "lblField0";
            this.lblField0.Text = "Mã phân công";
            this.lblField0.AutoSize = false;
            this.lblField0.Size = new Size(215, 20);
            this.lblField0.Location = new Point(6, 2);
            this.panField0.Controls.Add(this.lblField0);
            this.txtMaPC.Location = new Point(6, 27);
            this.txtMaPC.Size = new Size(210, 28);
            this.panField0.Controls.Add(this.txtMaPC);
            this.flowFields.Controls.Add(this.panField0);
            this.panField1 = new Panel();
            this.panField1.Name = "panField1";
            this.panField1.Size = new Size(230, 67);
            this.panField1.Margin = new Padding(5, 5, 5, 2);
            this.lblField1 = new Label();
            this.lblField1.Name = "lblField1";
            this.lblField1.Text = "Hướng dẫn viên";
            this.lblField1.AutoSize = false;
            this.lblField1.Size = new Size(215, 20);
            this.lblField1.Location = new Point(6, 2);
            this.panField1.Controls.Add(this.lblField1);
            this.cboHDV.Location = new Point(6, 27);
            this.cboHDV.Size = new Size(210, 28);
            this.panField1.Controls.Add(this.cboHDV);
            this.flowFields.Controls.Add(this.panField1);
            this.panField2 = new Panel();
            this.panField2.Name = "panField2";
            this.panField2.Size = new Size(230, 67);
            this.panField2.Margin = new Padding(5, 5, 5, 2);
            this.lblField2 = new Label();
            this.lblField2.Name = "lblField2";
            this.lblField2.Text = "Loại";
            this.lblField2.AutoSize = false;
            this.lblField2.Size = new Size(215, 20);
            this.lblField2.Location = new Point(6, 2);
            this.panField2.Controls.Add(this.lblField2);
            this.cboLoai.Location = new Point(6, 27);
            this.cboLoai.Size = new Size(210, 28);
            this.panField2.Controls.Add(this.cboLoai);
            this.flowFields.Controls.Add(this.panField2);
            this.panField3 = new Panel();
            this.panField3.Name = "panField3";
            this.panField3.Size = new Size(230, 67);
            this.panField3.Margin = new Padding(5, 5, 5, 2);
            this.lblField3 = new Label();
            this.lblField3.Name = "lblField3";
            this.lblField3.Text = "Chuyến / đoàn";
            this.lblField3.AutoSize = false;
            this.lblField3.Size = new Size(215, 20);
            this.lblField3.Location = new Point(6, 2);
            this.panField3.Controls.Add(this.lblField3);
            this.cboDoiTuong.Location = new Point(6, 27);
            this.cboDoiTuong.Size = new Size(210, 28);
            this.panField3.Controls.Add(this.cboDoiTuong);
            this.flowFields.Controls.Add(this.panField3);
            this.panField4 = new Panel();
            this.panField4.Name = "panField4";
            this.panField4.Size = new Size(230, 67);
            this.panField4.Margin = new Padding(5, 5, 5, 2);
            this.lblField4 = new Label();
            this.lblField4.Name = "lblField4";
            this.lblField4.Text = "Thù lao tour";
            this.lblField4.AutoSize = false;
            this.lblField4.Size = new Size(215, 20);
            this.lblField4.Location = new Point(6, 2);
            this.panField4.Controls.Add(this.lblField4);
            this.numThuLao.Location = new Point(6, 27);
            this.numThuLao.Size = new Size(210, 28);
            this.panField4.Controls.Add(this.numThuLao);
            this.flowFields.Controls.Add(this.panField4);
            this.panField5 = new Panel();
            this.panField5.Name = "panField5";
            this.panField5.Size = new Size(230, 67);
            this.panField5.Margin = new Padding(5, 5, 5, 2);
            this.lblField5 = new Label();
            this.lblField5.Name = "lblField5";
            this.lblField5.Text = "Phân công";
            this.lblField5.AutoSize = false;
            this.lblField5.Size = new Size(215, 20);
            this.lblField5.Location = new Point(6, 2);
            this.panField5.Controls.Add(this.lblField5);
            this.btnPhanCong.Location = new Point(6, 27);
            this.btnPhanCong.Size = new Size(210, 34);
            this.panField5.Controls.Add(this.btnPhanCong);
            this.flowFields.Controls.Add(this.panField5);
            this.mainLayout.Controls.Add(this.flowFields, 0, 1);
            this.mainLayout.Controls.Add(this.dgv, 0, 2);
            this.footerLayout = new FlowLayoutPanel();
            this.footerLayout.Name = "footerLayout";
            this.footerLayout.Dock = DockStyle.Fill;
            this.footerLayout.FlowDirection = FlowDirection.RightToLeft;
            this.footerLayout.Padding = new Padding(6);
            this.btnDong.Size = new Size(120, 35);
            this.footerLayout.Controls.Add(this.btnDong);
            this.mainLayout.Controls.Add(this.footerLayout, 0, 3);
            this.ResumeLayout(false);
        }
    }
}
