// Giao diện WinForms tạo bằng các control và container chuẩn để Visual Studio Designer hiển thị.
// Có thể chỉnh trực tiếp vị trí, kích thước, Text trong tab Design.
using System;
using System.Drawing;
using System.Windows.Forms;

namespace QuanLyCongTyDuLich.Forms
{
    public partial class FrmTour
    {
        private System.ComponentModel.IContainer components = null;
        private ComboBox cboTour;
        private TabControl tabTour;
        private DataGridView dgvTour;
        private TextBox txtMa;
        private TextBox txtTen;
        private NumericUpDown numNgay;
        private NumericUpDown numDem;
        private NumericUpDown numGia;
        private TextBox txtMoTa;
        private Button btnThemTour;
        private DataGridView dgvDiemDung;
        private NumericUpDown numThuTu;
        private TextBox txtDiemDung;
        private CheckBox chkDoiPT;
        private CheckBox chkAn;
        private CheckBox chkKS;
        private NumericUpDown numSao;
        private TextBox txtGhiChuDD;
        private Button btnThemDD;
        private DataGridView dgvChang;
        private NumericUpDown numChang;
        private ComboBox cboPT;
        private TextBox txtGhiChuPT;
        private Button btnThemChang;
        private DataGridView dgvTQ;
        private ComboBox cboDTQ;
        private NumericUpDown numThuTuTQ;
        private Button btnThemTQ;
        private Button btnDong;
        private TableLayoutPanel mainLayout;
        private Panel headerPanel;
        private Label lblTieuDe;
        private Label lblChonTour;
        private TabPage tabPage0;
        private TableLayoutPanel tabLayout0;
        private FlowLayoutPanel fieldsTab0;
        private Panel panTab0Field0;
        private Label lblTab0Field0;
        private Panel panTab0Field1;
        private Label lblTab0Field1;
        private Panel panTab0Field2;
        private Label lblTab0Field2;
        private Panel panTab0Field3;
        private Label lblTab0Field3;
        private Panel panTab0Field4;
        private Label lblTab0Field4;
        private Panel panTab0Field5;
        private Label lblTab0Field5;
        private Panel panTab0Field6;
        private Label lblTab0Field6;
        private TabPage tabPage1;
        private TableLayoutPanel tabLayout1;
        private FlowLayoutPanel fieldsTab1;
        private Panel panTab1Field0;
        private Label lblTab1Field0;
        private Panel panTab1Field1;
        private Label lblTab1Field1;
        private Panel panTab1Field5;
        private Label lblTab1Field5;
        private Panel panTab1Field6;
        private Label lblTab1Field6;
        private Panel panTab1Field7;
        private Label lblTab1Field7;
        private TabPage tabPage2;
        private TableLayoutPanel tabLayout2;
        private FlowLayoutPanel fieldsTab2;
        private Panel panTab2Field0;
        private Label lblTab2Field0;
        private Panel panTab2Field1;
        private Label lblTab2Field1;
        private Panel panTab2Field2;
        private Label lblTab2Field2;
        private Panel panTab2Field3;
        private Label lblTab2Field3;
        private TabPage tabPage3;
        private TableLayoutPanel tabLayout3;
        private FlowLayoutPanel fieldsTab3;
        private Panel panTab3Field0;
        private Label lblTab3Field0;
        private Panel panTab3Field1;
        private Label lblTab3Field1;
        private Panel panTab3Field2;
        private Label lblTab3Field2;
        private FlowLayoutPanel footerLayout;

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null) this.components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.cboTour = new ComboBox();
            this.cboTour.Name = "cboTour";
            this.cboTour.DropDownStyle = ComboBoxStyle.DropDownList;
            this.tabTour = new TabControl();
            this.tabTour.Name = "tabTour";
            this.dgvTour = new DataGridView();
            this.dgvTour.Name = "dgvTour";
            this.dgvTour.Dock = DockStyle.Fill;
            this.dgvTour.BackgroundColor = Color.White;
            this.dgvTour.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
            this.dgvTour.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvTour.MultiSelect = false;
            this.dgvTour.RowHeadersVisible = false;
            this.dgvTour.AllowUserToAddRows = false;
            this.dgvTour.AllowUserToDeleteRows = false;
            this.dgvTour.ReadOnly = true;
            this.txtMa = new TextBox();
            this.txtMa.Name = "txtMa";
            this.txtMa.Size = new Size(205, 29);
            this.txtTen = new TextBox();
            this.txtTen.Name = "txtTen";
            this.txtTen.Size = new Size(205, 29);
            this.numNgay = new NumericUpDown();
            this.numNgay.Name = "numNgay";
            this.numNgay.Maximum = 1000;
            this.numNgay.Minimum = 1;
            this.numNgay.Value = 3;
            this.numNgay.Size = new Size(205, 28);
            this.numDem = new NumericUpDown();
            this.numDem.Name = "numDem";
            this.numDem.Maximum = 1000;
            this.numDem.Minimum = 0;
            this.numDem.Size = new Size(205, 28);
            this.numGia = new NumericUpDown();
            this.numGia.Name = "numGia";
            this.numGia.Maximum = 100000000000M;
            this.numGia.Minimum = 0;
            this.numGia.Size = new Size(205, 28);
            this.txtMoTa = new TextBox();
            this.txtMoTa.Name = "txtMoTa";
            this.txtMoTa.Size = new Size(205, 29);
            this.btnThemTour = new Button();
            this.btnThemTour.Name = "btnThemTour";
            this.btnThemTour.Text = "Thêm tour";
            this.btnThemTour.Size = new Size(190, 36);
            this.btnThemTour.FlatStyle = FlatStyle.Standard;
            this.dgvDiemDung = new DataGridView();
            this.dgvDiemDung.Name = "dgvDiemDung";
            this.dgvDiemDung.Dock = DockStyle.Fill;
            this.dgvDiemDung.BackgroundColor = Color.White;
            this.dgvDiemDung.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
            this.dgvDiemDung.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvDiemDung.MultiSelect = false;
            this.dgvDiemDung.RowHeadersVisible = false;
            this.dgvDiemDung.AllowUserToAddRows = false;
            this.dgvDiemDung.AllowUserToDeleteRows = false;
            this.dgvDiemDung.ReadOnly = true;
            this.numThuTu = new NumericUpDown();
            this.numThuTu.Name = "numThuTu";
            this.numThuTu.Maximum = 1000;
            this.numThuTu.Minimum = 1;
            this.numThuTu.Size = new Size(205, 28);
            this.txtDiemDung = new TextBox();
            this.txtDiemDung.Name = "txtDiemDung";
            this.txtDiemDung.Size = new Size(205, 29);
            this.chkDoiPT = new CheckBox();
            this.chkDoiPT.Name = "chkDoiPT";
            this.chkDoiPT.AutoSize = true;
            this.chkAn = new CheckBox();
            this.chkAn.Name = "chkAn";
            this.chkAn.AutoSize = true;
            this.chkKS = new CheckBox();
            this.chkKS.Name = "chkKS";
            this.chkKS.AutoSize = true;
            this.numSao = new NumericUpDown();
            this.numSao.Name = "numSao";
            this.numSao.Maximum = 5;
            this.numSao.Minimum = 2;
            this.numSao.Value = 3;
            this.numSao.Size = new Size(205, 28);
            this.txtGhiChuDD = new TextBox();
            this.txtGhiChuDD.Name = "txtGhiChuDD";
            this.txtGhiChuDD.Size = new Size(205, 29);
            this.btnThemDD = new Button();
            this.btnThemDD.Name = "btnThemDD";
            this.btnThemDD.Text = "Thêm điểm dừng";
            this.btnThemDD.Size = new Size(190, 36);
            this.btnThemDD.FlatStyle = FlatStyle.Standard;
            this.dgvChang = new DataGridView();
            this.dgvChang.Name = "dgvChang";
            this.dgvChang.Dock = DockStyle.Fill;
            this.dgvChang.BackgroundColor = Color.White;
            this.dgvChang.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
            this.dgvChang.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvChang.MultiSelect = false;
            this.dgvChang.RowHeadersVisible = false;
            this.dgvChang.AllowUserToAddRows = false;
            this.dgvChang.AllowUserToDeleteRows = false;
            this.dgvChang.ReadOnly = true;
            this.numChang = new NumericUpDown();
            this.numChang.Name = "numChang";
            this.numChang.Maximum = 1000;
            this.numChang.Minimum = 1;
            this.numChang.Size = new Size(205, 28);
            this.cboPT = new ComboBox();
            this.cboPT.Name = "cboPT";
            this.cboPT.DropDownStyle = ComboBoxStyle.DropDownList;
            this.txtGhiChuPT = new TextBox();
            this.txtGhiChuPT.Name = "txtGhiChuPT";
            this.txtGhiChuPT.Size = new Size(205, 29);
            this.btnThemChang = new Button();
            this.btnThemChang.Name = "btnThemChang";
            this.btnThemChang.Text = "Gắn phương tiện";
            this.btnThemChang.Size = new Size(190, 36);
            this.btnThemChang.FlatStyle = FlatStyle.Standard;
            this.dgvTQ = new DataGridView();
            this.dgvTQ.Name = "dgvTQ";
            this.dgvTQ.Dock = DockStyle.Fill;
            this.dgvTQ.BackgroundColor = Color.White;
            this.dgvTQ.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.DisplayedCells;
            this.dgvTQ.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvTQ.MultiSelect = false;
            this.dgvTQ.RowHeadersVisible = false;
            this.dgvTQ.AllowUserToAddRows = false;
            this.dgvTQ.AllowUserToDeleteRows = false;
            this.dgvTQ.ReadOnly = true;
            this.cboDTQ = new ComboBox();
            this.cboDTQ.Name = "cboDTQ";
            this.cboDTQ.DropDownStyle = ComboBoxStyle.DropDownList;
            this.numThuTuTQ = new NumericUpDown();
            this.numThuTuTQ.Name = "numThuTuTQ";
            this.numThuTuTQ.Maximum = 1000;
            this.numThuTuTQ.Minimum = 1;
            this.numThuTuTQ.Size = new Size(205, 28);
            this.btnThemTQ = new Button();
            this.btnThemTQ.Name = "btnThemTQ";
            this.btnThemTQ.Text = "Gắn điểm TQ";
            this.btnThemTQ.Size = new Size(190, 36);
            this.btnThemTQ.FlatStyle = FlatStyle.Standard;
            this.btnDong = new Button();
            this.btnDong.Name = "btnDong";
            this.btnDong.Text = "Đóng";
            this.btnDong.Size = new Size(190, 36);
            this.btnDong.FlatStyle = FlatStyle.Standard;
            this.cboTour.SelectedIndexChanged += new EventHandler(this.cboTour_SelectedIndexChanged);
            this.btnThemTour.Click += new EventHandler(this.btnThemTour_Click);
            this.chkKS.CheckedChanged += new EventHandler(this.chkKS_CheckedChanged);
            this.btnThemDD.Click += new EventHandler(this.btnThemDD_Click);
            this.btnThemChang.Click += new EventHandler(this.btnThemChang_Click);
            this.btnThemTQ.Click += new EventHandler(this.btnThemTQ_Click);
            this.btnDong.Click += new EventHandler(this.btnDong_Click);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.ClientSize = new Size(1120, 760);
            this.MinimumSize = new Size(800, 600);
            this.StartPosition = FormStartPosition.CenterScreen;
            this.Font = new Font("Segoe UI", 9.5f);
            this.Text = "Quản lý tour - hành trình";
            this.Load += new EventHandler(this.FrmTour_Load);
            this.mainLayout = new TableLayoutPanel();
            this.mainLayout.Name = "mainLayout";
            this.mainLayout.Dock = DockStyle.Fill;
            this.mainLayout.Padding = new Padding(12);
            this.mainLayout.ColumnCount = 1;
            this.mainLayout.RowCount = 3;
            this.mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 70F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 55F));
            this.Controls.Add(this.mainLayout);
            this.headerPanel = new Panel();
            this.headerPanel.Name = "headerPanel";
            this.headerPanel.Dock = DockStyle.Fill;
            this.lblTieuDe = new Label();
            this.lblTieuDe.Name = "lblTieuDe";
            this.lblTieuDe.Text = "Quản lý tour - hành trình";
            this.lblTieuDe.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
            this.lblTieuDe.ForeColor = Color.FromArgb(33, 65, 94);
            this.lblTieuDe.Dock = DockStyle.Fill;
            this.lblTieuDe.TextAlign = ContentAlignment.MiddleCenter;
            this.headerPanel.Controls.Add(this.lblTieuDe);
            this.lblTieuDe.Dock = DockStyle.None;
            this.lblTieuDe.Location = new Point(4, 10);
            this.lblTieuDe.Size = new Size(440, 42);
            this.lblChonTour = new Label();
            this.lblChonTour.Name = "lblChonTour";
            this.lblChonTour.Text = "Tour đang chọn";
            this.lblChonTour.Location = new Point(500, 21);
            this.lblChonTour.Size = new Size(115, 30);
            this.headerPanel.Controls.Add(this.lblChonTour);
            this.cboTour.Location = new Point(620, 20);
            this.cboTour.Size = new Size(420, 30);
            this.headerPanel.Controls.Add(this.cboTour);
            this.mainLayout.Controls.Add(this.headerPanel, 0, 0);
            this.tabTour.Dock = DockStyle.Fill;
            this.tabPage0 = new TabPage();
            this.tabPage0.Name = "tabPage0";
            this.tabPage0.Text = "Tour";
            this.tabPage0.Padding = new Padding(8);
            this.tabLayout0 = new TableLayoutPanel();
            this.tabLayout0.Name = "tabLayout0";
            this.tabLayout0.Dock = DockStyle.Fill;
            this.tabLayout0.ColumnCount = 1;
            this.tabLayout0.RowCount = 2;
            this.tabLayout0.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.tabLayout0.RowStyles.Add(new RowStyle(SizeType.Percent, 64F));
            this.tabLayout0.RowStyles.Add(new RowStyle(SizeType.Percent, 36F));
            this.fieldsTab0 = new FlowLayoutPanel();
            this.fieldsTab0.Name = "fieldsTab0";
            this.fieldsTab0.Dock = DockStyle.Fill;
            this.fieldsTab0.AutoScroll = true;
            this.fieldsTab0.WrapContents = true;
            this.fieldsTab0.Padding = new Padding(6);
            this.fieldsTab0.FlowDirection = FlowDirection.LeftToRight;
            this.panTab0Field0 = new Panel();
            this.panTab0Field0.Name = "panTab0Field0";
            this.panTab0Field0.Size = new Size(230, 67);
            this.panTab0Field0.Margin = new Padding(5, 5, 5, 2);
            this.lblTab0Field0 = new Label();
            this.lblTab0Field0.Name = "lblTab0Field0";
            this.lblTab0Field0.Text = "Mã tour";
            this.lblTab0Field0.AutoSize = false;
            this.lblTab0Field0.Size = new Size(215, 20);
            this.lblTab0Field0.Location = new Point(6, 2);
            this.panTab0Field0.Controls.Add(this.lblTab0Field0);
            this.txtMa.Location = new Point(6, 27);
            this.txtMa.Size = new Size(210, 28);
            this.panTab0Field0.Controls.Add(this.txtMa);
            this.fieldsTab0.Controls.Add(this.panTab0Field0);
            this.panTab0Field1 = new Panel();
            this.panTab0Field1.Name = "panTab0Field1";
            this.panTab0Field1.Size = new Size(230, 67);
            this.panTab0Field1.Margin = new Padding(5, 5, 5, 2);
            this.lblTab0Field1 = new Label();
            this.lblTab0Field1.Name = "lblTab0Field1";
            this.lblTab0Field1.Text = "Tên tour";
            this.lblTab0Field1.AutoSize = false;
            this.lblTab0Field1.Size = new Size(215, 20);
            this.lblTab0Field1.Location = new Point(6, 2);
            this.panTab0Field1.Controls.Add(this.lblTab0Field1);
            this.txtTen.Location = new Point(6, 27);
            this.txtTen.Size = new Size(210, 28);
            this.panTab0Field1.Controls.Add(this.txtTen);
            this.fieldsTab0.Controls.Add(this.panTab0Field1);
            this.panTab0Field2 = new Panel();
            this.panTab0Field2.Name = "panTab0Field2";
            this.panTab0Field2.Size = new Size(230, 67);
            this.panTab0Field2.Margin = new Padding(5, 5, 5, 2);
            this.lblTab0Field2 = new Label();
            this.lblTab0Field2.Name = "lblTab0Field2";
            this.lblTab0Field2.Text = "Số ngày";
            this.lblTab0Field2.AutoSize = false;
            this.lblTab0Field2.Size = new Size(215, 20);
            this.lblTab0Field2.Location = new Point(6, 2);
            this.panTab0Field2.Controls.Add(this.lblTab0Field2);
            this.numNgay.Location = new Point(6, 27);
            this.numNgay.Size = new Size(210, 28);
            this.panTab0Field2.Controls.Add(this.numNgay);
            this.fieldsTab0.Controls.Add(this.panTab0Field2);
            this.panTab0Field3 = new Panel();
            this.panTab0Field3.Name = "panTab0Field3";
            this.panTab0Field3.Size = new Size(230, 67);
            this.panTab0Field3.Margin = new Padding(5, 5, 5, 2);
            this.lblTab0Field3 = new Label();
            this.lblTab0Field3.Name = "lblTab0Field3";
            this.lblTab0Field3.Text = "Số đêm";
            this.lblTab0Field3.AutoSize = false;
            this.lblTab0Field3.Size = new Size(215, 20);
            this.lblTab0Field3.Location = new Point(6, 2);
            this.panTab0Field3.Controls.Add(this.lblTab0Field3);
            this.numDem.Location = new Point(6, 27);
            this.numDem.Size = new Size(210, 28);
            this.panTab0Field3.Controls.Add(this.numDem);
            this.fieldsTab0.Controls.Add(this.panTab0Field3);
            this.panTab0Field4 = new Panel();
            this.panTab0Field4.Name = "panTab0Field4";
            this.panTab0Field4.Size = new Size(230, 67);
            this.panTab0Field4.Margin = new Padding(5, 5, 5, 2);
            this.lblTab0Field4 = new Label();
            this.lblTab0Field4.Name = "lblTab0Field4";
            this.lblTab0Field4.Text = "Đơn giá / khách";
            this.lblTab0Field4.AutoSize = false;
            this.lblTab0Field4.Size = new Size(215, 20);
            this.lblTab0Field4.Location = new Point(6, 2);
            this.panTab0Field4.Controls.Add(this.lblTab0Field4);
            this.numGia.Location = new Point(6, 27);
            this.numGia.Size = new Size(210, 28);
            this.panTab0Field4.Controls.Add(this.numGia);
            this.fieldsTab0.Controls.Add(this.panTab0Field4);
            this.panTab0Field5 = new Panel();
            this.panTab0Field5.Name = "panTab0Field5";
            this.panTab0Field5.Size = new Size(230, 67);
            this.panTab0Field5.Margin = new Padding(5, 5, 5, 2);
            this.lblTab0Field5 = new Label();
            this.lblTab0Field5.Name = "lblTab0Field5";
            this.lblTab0Field5.Text = "Mô tả";
            this.lblTab0Field5.AutoSize = false;
            this.lblTab0Field5.Size = new Size(215, 20);
            this.lblTab0Field5.Location = new Point(6, 2);
            this.panTab0Field5.Controls.Add(this.lblTab0Field5);
            this.txtMoTa.Location = new Point(6, 27);
            this.txtMoTa.Size = new Size(210, 28);
            this.panTab0Field5.Controls.Add(this.txtMoTa);
            this.fieldsTab0.Controls.Add(this.panTab0Field5);
            this.panTab0Field6 = new Panel();
            this.panTab0Field6.Name = "panTab0Field6";
            this.panTab0Field6.Size = new Size(230, 67);
            this.panTab0Field6.Margin = new Padding(5, 5, 5, 2);
            this.lblTab0Field6 = new Label();
            this.lblTab0Field6.Name = "lblTab0Field6";
            this.lblTab0Field6.Text = "Thêm tour";
            this.lblTab0Field6.AutoSize = false;
            this.lblTab0Field6.Size = new Size(215, 20);
            this.lblTab0Field6.Location = new Point(6, 2);
            this.panTab0Field6.Controls.Add(this.lblTab0Field6);
            this.btnThemTour.Location = new Point(6, 27);
            this.btnThemTour.Size = new Size(210, 34);
            this.panTab0Field6.Controls.Add(this.btnThemTour);
            this.fieldsTab0.Controls.Add(this.panTab0Field6);
            this.tabLayout0.Controls.Add(this.dgvTour, 0, 0);
            this.tabLayout0.Controls.Add(this.fieldsTab0, 0, 1);
            this.tabPage0.Controls.Add(this.tabLayout0);
            this.tabTour.Controls.Add(this.tabPage0);
            this.tabPage1 = new TabPage();
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Text = "Điểm dừng";
            this.tabPage1.Padding = new Padding(8);
            this.tabLayout1 = new TableLayoutPanel();
            this.tabLayout1.Name = "tabLayout1";
            this.tabLayout1.Dock = DockStyle.Fill;
            this.tabLayout1.ColumnCount = 1;
            this.tabLayout1.RowCount = 2;
            this.tabLayout1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.tabLayout1.RowStyles.Add(new RowStyle(SizeType.Percent, 64F));
            this.tabLayout1.RowStyles.Add(new RowStyle(SizeType.Percent, 36F));
            this.fieldsTab1 = new FlowLayoutPanel();
            this.fieldsTab1.Name = "fieldsTab1";
            this.fieldsTab1.Dock = DockStyle.Fill;
            this.fieldsTab1.AutoScroll = true;
            this.fieldsTab1.WrapContents = true;
            this.fieldsTab1.Padding = new Padding(6);
            this.fieldsTab1.FlowDirection = FlowDirection.LeftToRight;
            this.panTab1Field0 = new Panel();
            this.panTab1Field0.Name = "panTab1Field0";
            this.panTab1Field0.Size = new Size(230, 67);
            this.panTab1Field0.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field0 = new Label();
            this.lblTab1Field0.Name = "lblTab1Field0";
            this.lblTab1Field0.Text = "Thứ tự";
            this.lblTab1Field0.AutoSize = false;
            this.lblTab1Field0.Size = new Size(215, 20);
            this.lblTab1Field0.Location = new Point(6, 2);
            this.panTab1Field0.Controls.Add(this.lblTab1Field0);
            this.numThuTu.Location = new Point(6, 27);
            this.numThuTu.Size = new Size(210, 28);
            this.panTab1Field0.Controls.Add(this.numThuTu);
            this.fieldsTab1.Controls.Add(this.panTab1Field0);
            this.panTab1Field1 = new Panel();
            this.panTab1Field1.Name = "panTab1Field1";
            this.panTab1Field1.Size = new Size(230, 67);
            this.panTab1Field1.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field1 = new Label();
            this.lblTab1Field1.Name = "lblTab1Field1";
            this.lblTab1Field1.Text = "Tên điểm dừng";
            this.lblTab1Field1.AutoSize = false;
            this.lblTab1Field1.Size = new Size(215, 20);
            this.lblTab1Field1.Location = new Point(6, 2);
            this.panTab1Field1.Controls.Add(this.lblTab1Field1);
            this.txtDiemDung.Location = new Point(6, 27);
            this.txtDiemDung.Size = new Size(210, 28);
            this.panTab1Field1.Controls.Add(this.txtDiemDung);
            this.fieldsTab1.Controls.Add(this.panTab1Field1);
            this.chkDoiPT.Text = "Đổi phương tiện";
            this.chkDoiPT.Margin = new Padding(14, 22, 12, 9);
            this.fieldsTab1.Controls.Add(this.chkDoiPT);
            this.chkAn.Text = "Có nơi ăn";
            this.chkAn.Margin = new Padding(14, 22, 12, 9);
            this.fieldsTab1.Controls.Add(this.chkAn);
            this.chkKS.Text = "Có khách sạn";
            this.chkKS.Margin = new Padding(14, 22, 12, 9);
            this.fieldsTab1.Controls.Add(this.chkKS);
            this.panTab1Field5 = new Panel();
            this.panTab1Field5.Name = "panTab1Field5";
            this.panTab1Field5.Size = new Size(230, 67);
            this.panTab1Field5.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field5 = new Label();
            this.lblTab1Field5.Name = "lblTab1Field5";
            this.lblTab1Field5.Text = "Hạng sao";
            this.lblTab1Field5.AutoSize = false;
            this.lblTab1Field5.Size = new Size(215, 20);
            this.lblTab1Field5.Location = new Point(6, 2);
            this.panTab1Field5.Controls.Add(this.lblTab1Field5);
            this.numSao.Location = new Point(6, 27);
            this.numSao.Size = new Size(210, 28);
            this.panTab1Field5.Controls.Add(this.numSao);
            this.fieldsTab1.Controls.Add(this.panTab1Field5);
            this.panTab1Field6 = new Panel();
            this.panTab1Field6.Name = "panTab1Field6";
            this.panTab1Field6.Size = new Size(230, 67);
            this.panTab1Field6.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field6 = new Label();
            this.lblTab1Field6.Name = "lblTab1Field6";
            this.lblTab1Field6.Text = "Ghi chú";
            this.lblTab1Field6.AutoSize = false;
            this.lblTab1Field6.Size = new Size(215, 20);
            this.lblTab1Field6.Location = new Point(6, 2);
            this.panTab1Field6.Controls.Add(this.lblTab1Field6);
            this.txtGhiChuDD.Location = new Point(6, 27);
            this.txtGhiChuDD.Size = new Size(210, 28);
            this.panTab1Field6.Controls.Add(this.txtGhiChuDD);
            this.fieldsTab1.Controls.Add(this.panTab1Field6);
            this.panTab1Field7 = new Panel();
            this.panTab1Field7.Name = "panTab1Field7";
            this.panTab1Field7.Size = new Size(230, 67);
            this.panTab1Field7.Margin = new Padding(5, 5, 5, 2);
            this.lblTab1Field7 = new Label();
            this.lblTab1Field7.Name = "lblTab1Field7";
            this.lblTab1Field7.Text = "Thêm điểm dừng";
            this.lblTab1Field7.AutoSize = false;
            this.lblTab1Field7.Size = new Size(215, 20);
            this.lblTab1Field7.Location = new Point(6, 2);
            this.panTab1Field7.Controls.Add(this.lblTab1Field7);
            this.btnThemDD.Location = new Point(6, 27);
            this.btnThemDD.Size = new Size(210, 34);
            this.panTab1Field7.Controls.Add(this.btnThemDD);
            this.fieldsTab1.Controls.Add(this.panTab1Field7);
            this.tabLayout1.Controls.Add(this.dgvDiemDung, 0, 0);
            this.tabLayout1.Controls.Add(this.fieldsTab1, 0, 1);
            this.tabPage1.Controls.Add(this.tabLayout1);
            this.tabTour.Controls.Add(this.tabPage1);
            this.tabPage2 = new TabPage();
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Text = "Phương tiện theo chặng";
            this.tabPage2.Padding = new Padding(8);
            this.tabLayout2 = new TableLayoutPanel();
            this.tabLayout2.Name = "tabLayout2";
            this.tabLayout2.Dock = DockStyle.Fill;
            this.tabLayout2.ColumnCount = 1;
            this.tabLayout2.RowCount = 2;
            this.tabLayout2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.tabLayout2.RowStyles.Add(new RowStyle(SizeType.Percent, 64F));
            this.tabLayout2.RowStyles.Add(new RowStyle(SizeType.Percent, 36F));
            this.fieldsTab2 = new FlowLayoutPanel();
            this.fieldsTab2.Name = "fieldsTab2";
            this.fieldsTab2.Dock = DockStyle.Fill;
            this.fieldsTab2.AutoScroll = true;
            this.fieldsTab2.WrapContents = true;
            this.fieldsTab2.Padding = new Padding(6);
            this.fieldsTab2.FlowDirection = FlowDirection.LeftToRight;
            this.panTab2Field0 = new Panel();
            this.panTab2Field0.Name = "panTab2Field0";
            this.panTab2Field0.Size = new Size(230, 67);
            this.panTab2Field0.Margin = new Padding(5, 5, 5, 2);
            this.lblTab2Field0 = new Label();
            this.lblTab2Field0.Name = "lblTab2Field0";
            this.lblTab2Field0.Text = "Chặng thứ";
            this.lblTab2Field0.AutoSize = false;
            this.lblTab2Field0.Size = new Size(215, 20);
            this.lblTab2Field0.Location = new Point(6, 2);
            this.panTab2Field0.Controls.Add(this.lblTab2Field0);
            this.numChang.Location = new Point(6, 27);
            this.numChang.Size = new Size(210, 28);
            this.panTab2Field0.Controls.Add(this.numChang);
            this.fieldsTab2.Controls.Add(this.panTab2Field0);
            this.panTab2Field1 = new Panel();
            this.panTab2Field1.Name = "panTab2Field1";
            this.panTab2Field1.Size = new Size(230, 67);
            this.panTab2Field1.Margin = new Padding(5, 5, 5, 2);
            this.lblTab2Field1 = new Label();
            this.lblTab2Field1.Name = "lblTab2Field1";
            this.lblTab2Field1.Text = "Phương tiện";
            this.lblTab2Field1.AutoSize = false;
            this.lblTab2Field1.Size = new Size(215, 20);
            this.lblTab2Field1.Location = new Point(6, 2);
            this.panTab2Field1.Controls.Add(this.lblTab2Field1);
            this.cboPT.Location = new Point(6, 27);
            this.cboPT.Size = new Size(210, 28);
            this.panTab2Field1.Controls.Add(this.cboPT);
            this.fieldsTab2.Controls.Add(this.panTab2Field1);
            this.panTab2Field2 = new Panel();
            this.panTab2Field2.Name = "panTab2Field2";
            this.panTab2Field2.Size = new Size(230, 67);
            this.panTab2Field2.Margin = new Padding(5, 5, 5, 2);
            this.lblTab2Field2 = new Label();
            this.lblTab2Field2.Name = "lblTab2Field2";
            this.lblTab2Field2.Text = "Ghi chú";
            this.lblTab2Field2.AutoSize = false;
            this.lblTab2Field2.Size = new Size(215, 20);
            this.lblTab2Field2.Location = new Point(6, 2);
            this.panTab2Field2.Controls.Add(this.lblTab2Field2);
            this.txtGhiChuPT.Location = new Point(6, 27);
            this.txtGhiChuPT.Size = new Size(210, 28);
            this.panTab2Field2.Controls.Add(this.txtGhiChuPT);
            this.fieldsTab2.Controls.Add(this.panTab2Field2);
            this.panTab2Field3 = new Panel();
            this.panTab2Field3.Name = "panTab2Field3";
            this.panTab2Field3.Size = new Size(230, 67);
            this.panTab2Field3.Margin = new Padding(5, 5, 5, 2);
            this.lblTab2Field3 = new Label();
            this.lblTab2Field3.Name = "lblTab2Field3";
            this.lblTab2Field3.Text = "Gắn phương tiện";
            this.lblTab2Field3.AutoSize = false;
            this.lblTab2Field3.Size = new Size(215, 20);
            this.lblTab2Field3.Location = new Point(6, 2);
            this.panTab2Field3.Controls.Add(this.lblTab2Field3);
            this.btnThemChang.Location = new Point(6, 27);
            this.btnThemChang.Size = new Size(210, 34);
            this.panTab2Field3.Controls.Add(this.btnThemChang);
            this.fieldsTab2.Controls.Add(this.panTab2Field3);
            this.tabLayout2.Controls.Add(this.dgvChang, 0, 0);
            this.tabLayout2.Controls.Add(this.fieldsTab2, 0, 1);
            this.tabPage2.Controls.Add(this.tabLayout2);
            this.tabTour.Controls.Add(this.tabPage2);
            this.tabPage3 = new TabPage();
            this.tabPage3.Name = "tabPage3";
            this.tabPage3.Text = "Điểm tham quan";
            this.tabPage3.Padding = new Padding(8);
            this.tabLayout3 = new TableLayoutPanel();
            this.tabLayout3.Name = "tabLayout3";
            this.tabLayout3.Dock = DockStyle.Fill;
            this.tabLayout3.ColumnCount = 1;
            this.tabLayout3.RowCount = 2;
            this.tabLayout3.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.tabLayout3.RowStyles.Add(new RowStyle(SizeType.Percent, 64F));
            this.tabLayout3.RowStyles.Add(new RowStyle(SizeType.Percent, 36F));
            this.fieldsTab3 = new FlowLayoutPanel();
            this.fieldsTab3.Name = "fieldsTab3";
            this.fieldsTab3.Dock = DockStyle.Fill;
            this.fieldsTab3.AutoScroll = true;
            this.fieldsTab3.WrapContents = true;
            this.fieldsTab3.Padding = new Padding(6);
            this.fieldsTab3.FlowDirection = FlowDirection.LeftToRight;
            this.panTab3Field0 = new Panel();
            this.panTab3Field0.Name = "panTab3Field0";
            this.panTab3Field0.Size = new Size(230, 67);
            this.panTab3Field0.Margin = new Padding(5, 5, 5, 2);
            this.lblTab3Field0 = new Label();
            this.lblTab3Field0.Name = "lblTab3Field0";
            this.lblTab3Field0.Text = "Điểm tham quan";
            this.lblTab3Field0.AutoSize = false;
            this.lblTab3Field0.Size = new Size(215, 20);
            this.lblTab3Field0.Location = new Point(6, 2);
            this.panTab3Field0.Controls.Add(this.lblTab3Field0);
            this.cboDTQ.Location = new Point(6, 27);
            this.cboDTQ.Size = new Size(210, 28);
            this.panTab3Field0.Controls.Add(this.cboDTQ);
            this.fieldsTab3.Controls.Add(this.panTab3Field0);
            this.panTab3Field1 = new Panel();
            this.panTab3Field1.Name = "panTab3Field1";
            this.panTab3Field1.Size = new Size(230, 67);
            this.panTab3Field1.Margin = new Padding(5, 5, 5, 2);
            this.lblTab3Field1 = new Label();
            this.lblTab3Field1.Name = "lblTab3Field1";
            this.lblTab3Field1.Text = "Thứ tự";
            this.lblTab3Field1.AutoSize = false;
            this.lblTab3Field1.Size = new Size(215, 20);
            this.lblTab3Field1.Location = new Point(6, 2);
            this.panTab3Field1.Controls.Add(this.lblTab3Field1);
            this.numThuTuTQ.Location = new Point(6, 27);
            this.numThuTuTQ.Size = new Size(210, 28);
            this.panTab3Field1.Controls.Add(this.numThuTuTQ);
            this.fieldsTab3.Controls.Add(this.panTab3Field1);
            this.panTab3Field2 = new Panel();
            this.panTab3Field2.Name = "panTab3Field2";
            this.panTab3Field2.Size = new Size(230, 67);
            this.panTab3Field2.Margin = new Padding(5, 5, 5, 2);
            this.lblTab3Field2 = new Label();
            this.lblTab3Field2.Name = "lblTab3Field2";
            this.lblTab3Field2.Text = "Gắn điểm TQ";
            this.lblTab3Field2.AutoSize = false;
            this.lblTab3Field2.Size = new Size(215, 20);
            this.lblTab3Field2.Location = new Point(6, 2);
            this.panTab3Field2.Controls.Add(this.lblTab3Field2);
            this.btnThemTQ.Location = new Point(6, 27);
            this.btnThemTQ.Size = new Size(210, 34);
            this.panTab3Field2.Controls.Add(this.btnThemTQ);
            this.fieldsTab3.Controls.Add(this.panTab3Field2);
            this.tabLayout3.Controls.Add(this.dgvTQ, 0, 0);
            this.tabLayout3.Controls.Add(this.fieldsTab3, 0, 1);
            this.tabPage3.Controls.Add(this.tabLayout3);
            this.tabTour.Controls.Add(this.tabPage3);
            this.mainLayout.Controls.Add(this.tabTour, 0, 1);
            this.footerLayout = new FlowLayoutPanel();
            this.footerLayout.Name = "footerLayout";
            this.footerLayout.Dock = DockStyle.Fill;
            this.footerLayout.FlowDirection = FlowDirection.RightToLeft;
            this.footerLayout.Padding = new Padding(6);
            this.btnDong.Size = new Size(120, 35);
            this.footerLayout.Controls.Add(this.btnDong);
            this.mainLayout.Controls.Add(this.footerLayout, 0, 2);
            this.ResumeLayout(false);
        }
    }
}
